import {localize} from './localize';
import packageInfo from '../package.json';
import {useEffect,useRef,useState} from 'react';
import {Activity,ArrowRight,BarChart3,Check,ChevronLeft,ChevronRight,Download,Eye,FlaskConical,Layers,LoaderCircle,Play,RotateCcw,Settings2,ShieldCheck,Spade,Table2,Terminal,Upload,Workflow} from 'lucide-react';
import {api,ApiResponseError,BackendConnectionError,backendConnectionMessage,Card,defaultRules,download,Event,Rules,Snapshot} from './api';
import VisionTools from './VisionTools';
import CountingPanel from './CountingPanel';
import ExperimentSummary from './ExperimentSummary';
import VisionReport,{DetectionOverlay} from './VisionReport';
import {LiveAdvisor} from './LiveVision';
import MultiTable from './MultiTable';
import StrategyLibrary from './StrategyLibrary';
import ImageAdvisor from './ImageAdvisor';
import Brand from './Brand';
import ToolsPanel from './ToolsPanel';
import PokerLab from './PokerLab';
import {Setup,Guide,ReuseConfiguration} from './Setup';
import {readRules,saveRules,isFirstVisit} from './preferences';
import LanguageSelector from './LanguageSelector';
import {getLanguage} from './i18n';

const nav=[{id:'poker',label:'Texas Hold’em lab',icon:Spade},{id:'live',label:'Live vision',icon:Eye},{id:'image',label:'Image & manual advice',icon:Upload},{id:'strategy',label:'Basic strategy library',icon:Layers},{id:'table',label:'Tavolo & decisioni',icon:Table2},{id:'counting',label:'Sistemi di conteggio',icon:BarChart3},{id:'vision',label:'Perception lab',icon:Eye},{id:'replay',label:'Replay & eventi',icon:Workflow},{id:'experiments',label:'Esperimenti',icon:FlaskConical},{id:'rules',label:'Regolamento',icon:Settings2},{id:'tools',label:'Programs & extensions',icon:Terminal},{id:'roadmap',label:'Roadmap completa',icon:Layers}];
const titles:Record<string,[string,string]>={poker:['Understand the hand. Measure equity.','Texas Hold’em with ranks, suits and explicit opponent ranges.'],tools:['Set up the way you play.','Essential programs, local models and optional helpers.'],image:['An image. A clearer decision.','Paste, drop or confirm the cards you can see.'],strategy:['The strategy, at a glance.','Hard totals, soft hands, pairs and every starting rank combination.'],live:['Watch the game. Follow every decision.','Continuous video, persistent card tracking and probability estimates.'],table:['Ogni carta, una prova.','Esplora il gioco. Confronta le decisioni. Ricostruisci il perché.'],counting:['La stessa shoe, più sistemi.','Confronta conteggi e tag sugli stessi eventi osservati.'],vision:['Dai pixel allo stato.','Riconoscimento e tracking sul nostro simulatore controllato.'],replay:['Il gioco, ricostruibile.','Ispeziona ogni evento e torna al punto in cui lo stato è cambiato.'],experiments:['Le idee incontrano i numeri.','Esperimenti riproducibili con seed, regole e incertezza dichiarati.'],rules:['Le regole cambiano il gioco.','Configura un regolamento esplicito per il simulatore e il solver.'],roadmap:['Un laboratorio completo.','Tutti i requisiti integrati, con evidenze e stato di verifica.']};
const labels:Record<string,string>={hit:'Carta',stand:'Stai',double:'Raddoppia',split:'Dividi',surrender:'Resa',insurance:'Assicurazione',decline_insurance:'Rifiuta assicurazione',continue:'Continua',deal:'Distribuisci'};
const symbols:Record<string,string>={S:'♠',H:'♥',D:'♦',C:'♣',spades:'♠',hearts:'♥',diamonds:'♦',clubs:'♣','♠':'♠','♥':'♥','♦':'♦','♣':'♣'};
const fmt=(x:unknown,d=3)=>typeof x==='number'&&Number.isFinite(x)?x.toFixed(d):'—';
const pretty=(x:unknown)=>JSON.stringify(x,null,2);
function PlayingCard({card,index=0,interval=60,design='classic'}:{card:Card;index?:number;interval?:number;design?:string}){
 const suit=symbols[card.suit||'S']||card.suit;const red=['♥','♦'].includes(suit||'');
 return localize(<div className={'playing-card '+(card.face_down?'back':red?'red':'')} style={{animationDelay:index*interval+'ms',animationDuration:Math.max(80,interval*2)+'ms'}} aria-label={card.face_down?'Carta coperta':(card.rank+' '+suit)}>
 {card.face_down?<div className="back-pattern"><Spade size={30}/></div>:<><div className="corner"><b>{card.rank}</b><span>{suit}</span></div><span className={design==='minimal'?'large-rank':'large-suit'}>{design==='minimal'?card.rank:suit}</span><div className="corner inverted"><b>{card.rank}</b><span>{suit}</span></div></>}
 </div>);
}
function Empty({children}:{children:React.ReactNode}){return localize(<div className="empty">{children}</div>)}
function Badge({children,kind='neutral'}:{children:React.ReactNode;kind?:string}){return localize(<span className={'badge '+kind}>{children}</span>)}
export default function App(){
 const [tab,setTab]=useState('live'),[session,setSession]=useState<Snapshot|null>(null),[rules,setRules]=useState<Rules>(readRules),[seed,setSeed]=useState(42),[bet,setBet]=useState(1);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[decision,setDecision]=useState<any>(null),[calculating,setCalculating]=useState(false),[online,setOnline]=useState(false),[connecting,setConnecting]=useState(false);
 const [events,setEvents]=useState<Event[]>([]),[cursor,setCursor]=useState(0),[replay,setReplay]=useState<any>(null),[perception,setPerception]=useState<any>(null),[imageVersion,setImageVersion]=useState(0);
 const [theme,setTheme]=useState('black'),[blur,setBlur]=useState(0),[overlap,setOverlap]=useState(0),[rounds,setRounds]=useState(200),[withComposition,setWithComposition]=useState(false),[experiment,setExperiment]=useState<any>(null),[roadmap,setRoadmap]=useState<any>(null);
 const [outcomes,setOutcomes]=useState<any>(null);
 const [analysisBudget,setAnalysisBudget]=useState(1500),[cardDesign,setCardDesign]=useState('classic'),[dealInterval,setDealInterval]=useState(60);
 const generation=useRef(0),connectionAttempt=useRef(0),uploadRef=useRef<HTMLInputElement>(null),replayUpload=useRef<HTMLInputElement>(null);
 const [,setLanguage]=useState(getLanguage());
 const sid=session?.session_id;
 const firstVisit=useRef(isFirstVisit());
 const [confirmReset,setConfirmReset]=useState(false);
 const [setup,setSetup]=useState(firstVisit.current),[guide,setGuide]=useState(false),[pastedFile,setPastedFile]=useState<File|null>(null);
 useEffect(()=>{saveRules(rules)},[rules]);
 useEffect(()=>{const pasted=(event:ClipboardEvent)=>{const file=Array.from(event.clipboardData?.files||[]).find(f=>f.type.startsWith('image/'));if(file){event.preventDefault();setPastedFile(file);setTab('image')}};window.addEventListener('paste',pasted);return()=>window.removeEventListener('paste',pasted)},[]);
 useEffect(()=>{document.documentElement.lang=getLanguage()},[]);
 useEffect(()=>{setPerception(null)},[theme,blur,overlap,imageVersion,cardDesign]);
 const connect=async()=>{
  const attempt=++connectionAttempt.current;setConnecting(true);setError('');
  try{
   await api('/health');if(attempt!==connectionAttempt.current)return;setOnline(true);
   let state:Snapshot;
   if(sid){try{state=await api<Snapshot>('/sessions/'+sid)}catch(e){if(e instanceof ApiResponseError&&e.status===404)state=await api<Snapshot>('/sessions',{seed,rules});else throw e}}
   else state=await api<Snapshot>('/sessions',{seed,rules});
   if(attempt!==connectionAttempt.current)return;
   generation.current++;setCalculating(false);setSession(state);setOutcomes(null);setDecision(null);setPerception(null);
  }catch(e){if(attempt===connectionAttempt.current){if(e instanceof BackendConnectionError)setOnline(false);setError(e instanceof Error?e.message:String(e))}}
  finally{if(attempt===connectionAttempt.current)setConnecting(false)}
 };
 useEffect(()=>{
  const unavailable=()=>{setOnline(false);setDecision(null);setCalculating(false);generation.current++;setError(backendConnectionMessage)};
  window.addEventListener('bjlab:backend-unavailable',unavailable);void connect();
  return()=>{window.removeEventListener('bjlab:backend-unavailable',unavailable);connectionAttempt.current++};
 },[]);
 useEffect(()=>{if(tab==='replay'&&sid)api<Event[]>('/sessions/'+sid+'/events').then(value=>{const data=Array.isArray(value)?value:(value as any).events;setEvents(data||[]);setCursor(Math.max(0,(data||[]).length-1));}).catch(e=>setError(e.message));if(tab==='roadmap')api('/roadmap').then(setRoadmap).catch(e=>setError(e.message));},[tab,sid,session?.events_count]);
 const task=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const analyze=async(s:Snapshot)=>{const gen=++generation.current;setDecision(null);setOutcomes(null);if(!['player','insurance','early_surrender'].includes(s.phase)){setCalculating(false);return}setCalculating(true);if(s.phase==='player')void api('/sessions/'+s.session_id+'/outcomes',{}).then(value=>{if(gen===generation.current&&value.events_count===s.events_count)setOutcomes(value.decision)}).catch(()=>{});try{const d=await api('/sessions/'+s.session_id+'/analyze',{timeout_ms:analysisBudget,max_nodes:analysisBudget>1500?150000:60000});if(gen===generation.current){if(!d.result)throw new Error(d.error||'Analisi non disponibile.');setDecision({...d.result,basic_strategy:d.comparison?.basic,hilo_strategy:d.comparison?.hilo,notes:d.result.warnings})}}catch(e){if(gen===generation.current)setError(e instanceof Error?e.message:String(e))}finally{if(gen===generation.current)setCalculating(false)}};
 const performReset=()=>task(async()=>{const s=await api<Snapshot>('/sessions',{seed,rules});setSession(s);setOutcomes(null);setDecision(null);setPerception(null);setExperiment(null);generation.current++;setCalculating(false)});
 const reset=()=>{if(localStorage.getItem('bjlab.reuseRules')==='yes')void performReset();else setConfirmReset(true)};
 const deal=()=>task(async()=>{const s=await api<Snapshot>('/sessions/'+sid+'/deal',{bet});setSession(s);setOutcomes(null);setImageVersion(v=>v+1);void analyze(s)});
 const action=(name:string)=>task(async()=>{const s=await api<Snapshot>('/sessions/'+sid+'/action',{action:name});setSession(s);setOutcomes(null);setImageVersion(v=>v+1);void analyze(s)});
 const resultActions=decision?.actions||decision?.ev||decision?.action_evs||{};
 const decisions=Object.entries(resultActions).map(([name,val]:[string,any])=>({name:name.toLowerCase(),ev:typeof val==='number'?val:val?.ev,exact:typeof val==='object'?val?.exact:decision?.exact})).filter(x=>session?.available_actions.includes(x.name)||['hit','stand','double','split','surrender'].includes(x.name));
 const best=String((decision?.exact?decision?.best_action:null)||session?.advice?.best_action||'').toLowerCase();
 const nativeReport=session?{decision:outcomes,player:session.hands[session.active_hand||0]?.cards.filter(c=>!c.face_down).map(c=>c.rank)||[],dealer:session.dealer.cards.filter(c=>!c.face_down).map(c=>c.rank)||[],phase:session.phase,advice:decision?.exact&&decision.best_action?{...session.advice,best_action:decision.best_action,basis:'observed-composition'}:session.advice,observed_cards:session.shoe.seen,running_count:session.shoe.running_count,true_count:session.shoe.true_count,physical_remaining:session.shoe.remaining,count_scope:'from declared fresh shoe'}:null;
 const frameUrl=sid?'/api/sessions/'+sid+'/frame?theme='+theme+'&blur='+blur+'&overlap='+overlap+'&card_design='+cardDesign+'&v='+imageVersion:'';
 const selectEvent=async(i:number)=>{setCursor(i);try{setReplay(await api('/replay',{events:events.slice(0,i+1)}))}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const uploadImage=async(file:File)=>{const reader=new FileReader();reader.onload=()=>task(async()=>{const r=await api('/vision/upload',{image_base64:String(reader.result).split(',')[1]});setPerception(r)});reader.readAsDataURL(file)};
 const uploadEvents=async(file:File)=>task(async()=>{const value=JSON.parse(await file.text());const es=Array.isArray(value)?value:value.events; if(!Array.isArray(es))throw new Error('Il file deve contenere una lista di eventi.');setEvents(es);setCursor(es.length-1);setReplay(await api('/replay',{events:es}));});
 const patchRule=(key:keyof Rules,value:any)=>setRules(r=>({...r,[key]:value}));
 const shoe=session?.shoe;
 const runExperiment=()=>task(async()=>setExperiment(await api('/experiments',{rounds,seed,rules,policies:withComposition?['basic','hilo','composition']:['basic','hilo']})));
 return localize(<div className="app" onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault()}} onDrop={e=>{const file=e.dataTransfer.files[0];if(file?.type.startsWith('image/')){e.preventDefault();setPastedFile(file);setTab('image')}}}>
 <aside className="sidebar"><a className="brand" href="#"><Brand/></a><div className="nav-label">IL LABORATORIO</div><nav>{nav.map(n=><button key={n.id} className={tab===n.id?'selected':''} onClick={()=>setTab(n.id)}><n.icon size={18}/>{n.label}{tab===n.id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="research"><ShieldCheck size={18}/><span>Ambiente di ricerca<br/><small>Simulatore controllato</small></span></div><div className="version">BVL / {packageInfo.version} <span>LOCAL</span></div></div></aside>
 <main><header className="topbar"><div className="breadcrumb">LABORATORIO <ChevronRight size={12}/> <b>{nav.find(n=>n.id===tab)?.label}</b></div><div className="top-status"><button className="text-button" onClick={()=>setGuide(true)}>Quick guide</button><button className="text-button" onClick={()=>setSetup(true)}>Configure</button><LanguageSelector onChange={setLanguage}/><span className={'status-dot '+(online?'ok':'')}/>{online?'Backend connesso':connecting?'Connessione…':'Backend non raggiungibile'}<span className="divider"/><span>Seed {session?.seed??'—'}</span></div></header>
 <div className="page-head"><div><div className="eyebrow">OSSERVA · CALCOLA · VERIFICA</div><h1>{titles[tab][0]}</h1><p>{titles[tab][1]}</p></div><button className="button secondary" onClick={reset} disabled={busy||!online}><RotateCcw size={15}/>Nuova sessione</button></div>
 <div style={{display:tab==='live'?'block':'none'}}><MultiTable rules={rules} connected={online}/></div>
 {tab==='tools'&&<ToolsPanel/>}
  {tab==='strategy'&&<StrategyLibrary rules={rules}/>}
 {tab==='image'&&<ImageAdvisor rules={rules} connected={online} file={pastedFile}/>}
 {setup&&<Setup rules={rules} onClose={()=>setSetup(false)} onSave={value=>{setRules(value);setSetup(false);if(firstVisit.current){firstVisit.current=false;setGuide(true)}void task(async()=>{const state=await api<Snapshot>('/sessions',{seed,rules:value});setSession(state);setOutcomes(null);setDecision(null);generation.current++})}}/>}
 {confirmReset&&<ReuseConfiguration rules={rules} onClose={()=>setConfirmReset(false)} onConfirm={()=>{setConfirmReset(false);void performReset()}}/>}
 {guide&&<Guide onClose={()=>setGuide(false)}/>}
 {['table','vision'].includes(tab)&&<section className="simulation-options panel" aria-label="Aspetto del simulatore"><label>Design carte<select aria-label="Design carte" value={cardDesign} onChange={e=>setCardDesign(e.target.value)}><option value="classic">Classico</option><option value="minimal">Essenziale</option></select></label><label>Velocità distribuzione<select aria-label="Velocità distribuzione" value={dealInterval} onChange={e=>setDealInterval(Number(e.target.value))}><option value="0">Istantanea</option><option value="60">Rapida</option><option value="250">Lenta</option></select></label><small>Gli intervalli cambiano l’animazione delle carte; il seed mantiene lo stesso gioco.</small></section>}
 {!online&&<section className="panel connection-panel" role="status"><div><strong>Backend locale non connesso</strong><p>Per usare questa pagina esegui run.ps1 nella cartella dei sorgenti e tienilo aperto. L’app desktop avvia il proprio backend quando la apri.</p></div><button className="button primary" onClick={()=>void connect()} disabled={connecting}>{connecting?'Connessione…':'Riconnetti'}</button></section>}
 {error&&<div className="error" role="alert"><b>Operazione non completata</b><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
 {tab==='vision'&&<VisionTools connected={online} sid={sid} budget={analysisBudget} onResult={setPerception} canAnalyze={!perception||perception.deck_estimation?.source==='configured-session'} observation={perception}/>}
 {tab==='counting'&&<CountingPanel session={session}/>}
 {tab==='table'&&<>
 <div className="stats-row">
 {[['CARD SHOE',shoe?String(shoe.id):'—',shoe?shoe.decks+' mazzi · '+shoe.seen+' carte osservate':'In attesa'],['RUNNING COUNT',shoe?String(shoe.running_count):'—','Hi-Lo · eventi esposti'],['TRUE COUNT',fmt(shoe?.true_count,2),shoe?fmt(shoe.remaining/52,2)+' mazzi fisici rimasti':'Normalizzato ai mazzi rimasti'],['RISULTATO SESSIONE',fmt(session?.total_profit,2),session?'Round '+session.round_id+' · unità di puntata':'Nessuna mano giocata']].map(([l,v,d])=><div className="stat" key={l}><span>{l}</span><strong>{v}</strong><small>{d}</small></div>)}
 </div><div className="workbench"><section className="table-panel">
 <div className="panel-header"><h2><Table2 size={16}/>Simulatore</h2><Badge kind="green"><span className="status-dot ok"/> {session?.phase==='player'?'Turno giocatore':session?.phase==='settled'?'Mano conclusa':session?.phase==='insurance'?'Assicurazione':session?.phase==='early_surrender'?'Resa anticipata':'Pronto'}</Badge></div>
 <div className={'felt '+theme}><div className="felt-orbit"/><div className="table-caption">BLACKJACK PAYS {session?.rules.blackjack_payout===1.2?'6 : 5':'3 : 2'} <span>DEALER {session?.rules.hit_soft17?'HITS':'STANDS'} SOFT 17</span></div>
 <div className="dealer-zone"><div className="zone-label">BANCO <span>{session?.dealer.total!==null&&session?.dealer.total!==undefined?session.dealer.total:'?'}</span></div><div className="card-row">{session?.dealer.cards.map((c,i)=><PlayingCard key={c.id} card={c} index={i} interval={dealInterval} design={cardDesign}/>)}{!session?.dealer.cards.length&&<div className="card-slot"><Spade size={24}/></div>}</div></div>
 <div className="table-watermark"><Spade size={24}/><span>VISION LAB</span></div>
 <div className="player-zones">{session?.hands.length?session.hands.map((h,hi)=><div className={'player-zone '+(session.active_hand===hi?'active':'')} key={hi}><div className="card-row">{h.cards.map((c,i)=><PlayingCard key={c.id} card={c} index={i} interval={dealInterval} design={cardDesign}/>)}</div><div className="zone-label">MANO {hi+1}<span>{h.total}{h.soft?' / '+(h.total-10)+' soft':''}{h.cards.some(c=>c.rank==='A')&&' / A = 1 or 11'}</span></div><small>{h.status==='busted'?'Bust':h.status==='blackjack'?'Blackjack':h.status==='surrendered'?'Resa':h.status==='settled'?'Profitto '+fmt(h.profit,2):'Puntata '+h.bet}</small></div>):<div className="table-empty">Il tuo prossimo esperimento<br/><b>inizia con una mano.</b></div>}</div>
 </div><div className="table-controls"><label>Puntata <input type="number" min=".1" step=".5" value={bet} onChange={e=>setBet(Number(e.target.value))}/></label><div className="actions">{session&&['ready','settled'].includes(session.phase)?<button className="button primary" onClick={deal} disabled={busy||!online}><Play size={15}/>Distribuisci</button>:session?.available_actions.map(a=><button key={a} className={'button '+(a===best?'primary':'secondary')} onClick={()=>action(a)} disabled={busy||!online}>{labels[a]||a}</button>)}</div></div>
 {session?.phase==='settled'&&<div className="round-result">Mano conclusa <strong className={session.round_profit>=0?'positive':'negative'}>{session.round_profit>=0?'+':''}{fmt(session.round_profit,2)} unità</strong></div>}
 </section><section className="decision-panel"><div className="panel-header"><h2><Activity size={16}/>Decisioni & EV</h2><select className="budget-select" aria-label="Budget solver" value={analysisBudget} onChange={e=>setAnalysisBudget(Number(e.target.value))}><option value="1500">1.5 s</option><option value="5000">5 s</option><option value="15000">15 s</option></select><button className="icon-button" title="Ricalcola" onClick={()=>session&&void analyze(session)} disabled={!online||calculating||!['player','insurance','early_surrender'].includes(session?.phase||'')}><RotateCcw size={15}/></button></div>
 <LiveAdvisor report={nativeReport} stale={false}/>
 <details className="native-ev-details"><summary>Finite-pool EV calculation & precision</summary>
 {calculating?<Empty><LoaderCircle className="spin" size={25}/><strong>Calcolo degli EV</strong><span>Regole e carte osservabili della mano corrente.</span></Empty>:decisions.length?<><div className="recommendation"><span>{decision?.exact?'SOLUZIONE ESATTA':'ANALISI · PRECISIONE DICHIARATA'}</span><h3>{best?(labels[best]||best):'Confirm the cards'} {best&&<ArrowRight size={25}/>}</h3><small>{decision?.method||'Solver matematico'}</small></div><div className="ev-list">{decisions.map(d=><div className={'ev-row '+(d.name===best?'best':'')} key={d.name}><div>{d.name===best?<Check size={16}/>:<span className="ev-dot"/>}{labels[d.name]||d.name}</div><strong>{fmt(d.ev,5)}</strong></div>)}</div><div className="precision-note">{decision?.exact?'EV condizionato alle informazioni osservate.':decision?.error||decision?.status||'Consultare metodo e note per il livello di precisione.'}{decision?.latency_ms!==undefined&&<span>{fmt(decision.latency_ms,1)} ms</span>}</div>{decision?.notes&&<small className="notes">{Array.isArray(decision.notes)?decision.notes.join(' · '):String(decision.notes)}</small>}</>:<Empty><BarChart3 size={27}/><strong>{session?.phase==='settled'?'Esperimento concluso':'Una decisione alla volta'}</strong><span>Gli EV vengono calcolati quando è il turno del giocatore.</span></Empty>}
 </details><div className="comparison"><div className="section-label">CONFRONTO STRATEGIE</div>{[['Basic · replacement',decision?.basic_strategy||session?.advice?.basic_action],['Hi-Lo · chart',decision?.hilo_strategy||session?.advice?.count_action],['Composizione',best?labels[best]||best:null]].map(([l,v])=><div key={l}><span>{l}</span><b>{typeof v==='string'?labels[v.toLowerCase()]||v:'Non calcolata'}</b></div>)}</div></section></div>
 <div className="bottom-grid"><section className="panel composition"><div className="panel-header"><h2><Layers size={16}/>Pool non osservato</h2><small>Per valore · include carte nascoste</small></div><div className="composition-chart">{(shoe?.counts||Array(10).fill(0)).map((n,i)=><div key={i}><span className="bar-number">{n}</span><div className="bar-track"><div style={{height:Math.max(2,n/Math.max(...(shoe?.counts||[1]),1)*100)+'%'}}/></div><b>{['A','2','3','4','5','6','7','8','9','10'][i]}</b></div>)}</div></section><section className="panel integrity"><div className="panel-header"><h2><ShieldCheck size={16}/>Stato dello shoe</h2></div><div className="integrity-line"><span>Fonte dello stato</span><b>Simulatore nativo</b></div><div className="integrity-line"><span>Carte fisiche rimaste</span><b>{shoe?.remaining??'—'}</b></div><div className="integrity-line"><span>Carte non esposte</span><b>{shoe?.unknown_cards??'—'}</b></div><div className="integrity-line"><span>Penetrazione</span><b>{fmt((shoe?.penetration||0)*100,1)}%</b></div><div className="progress"><span style={{width:(shoe?.penetration||0)*100+'%'}}/></div><button className="text-button" onClick={()=>setTab('vision')}>Verifica attraverso i pixel <ArrowRight size={14}/></button></section></div>
 </>}
 {tab==='vision'&&<><div className="vision-toolbar panel"><label>Tema<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="black">Graphite</option><option value="green">Verde</option><option value="navy">Blu</option><option value="burgundy">Bordeaux</option></select></label><label>Blur <input type="range" min="0" max="4" step=".5" value={blur} onChange={e=>setBlur(Number(e.target.value))}/><span>{blur}px</span></label><label>Sovrapposizione<input type="range" min="0" max=".85" step=".05" value={overlap} onChange={e=>setOverlap(Number(e.target.value))}/><span>{Math.round(overlap*100)}%</span></label><button className="button primary" disabled={busy||!sid||!online} onClick={()=>task(async()=>setPerception(await api('/sessions/'+sid+'/perception',{frames:3,theme,blur,overlap,card_design:cardDesign})))}><Eye size={16}/>Analizza frame</button><button className="button secondary" onClick={()=>uploadRef.current?.click()}><Upload size={16}/>Carica immagine</button><input hidden type="file" ref={uploadRef} accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&void uploadImage(e.target.files[0])}/></div><VisionReport result={perception}/><div className="vision-grid"><section className="panel"><div className="panel-header"><h2>Frame controllato</h2><Badge>PIXEL INPUT</Badge></div>{sid?<div className="vision-image-wrap"><img className="vision-frame" src={frameUrl} alt="Frame del simulatore per riconoscimento carte"/>{perception?.frame_source==='still-repeat'&&<DetectionOverlay detections={perception.detections||[]}/>}</div>:<Empty>Nessuna sessione</Empty>}<p className="panel-caption">Le etichette del simulatore restano separate dal detector. Il frame contiene soltanto le carte esposte.</p></section><section className="panel"><div className="panel-header"><h2>Percezione & tracking</h2></div>{perception?<><div className="detection-list">{(perception.detections||[]).map((d:any,i:number)=><div key={i}><b>{d.face_down?'Coperta':d.rank+' '+(symbols[d.suit]||d.suit)}</b><span>{d.zone||'—'}</span><span>score {fmt(d.score??d.confidence,3)}</span></div>)}</div><details open><summary>Stato ricostruito e gate</summary><pre>{pretty(perception.state||perception)}</pre></details><button className="button secondary" onClick={()=>download('perception.json',perception)}><Download size={14}/>Esporta risultato</button></>:<Empty><Eye size={28}/><strong>Osservazioni prima delle decisioni</strong><span>Avvia l'analisi per vedere detections, eventi e integrità dello stato.</span></Empty>}</section></div></>}
 {tab==='replay'&&<><div className="panel replay-toolbar"><button className="button secondary" onClick={()=>sid&&window.open('/api/sessions/'+sid+'/export?format=json','_blank')}><Download size={15}/>Sessione JSON</button><button className="button secondary" onClick={()=>sid&&window.open('/api/sessions/'+sid+'/export?format=csv','_blank')}><Download size={15}/>Eventi CSV</button><button className="button secondary" onClick={()=>replayUpload.current?.click()}><Upload size={15}/>Importa replay</button><input hidden ref={replayUpload} type="file" accept=".json" onChange={e=>e.target.files?.[0]&&void uploadEvents(e.target.files[0])}/><span>{events.length} eventi disponibili</span></div><section className="panel"><div className="timeline-controls"><button className="icon-button" disabled={!cursor} onClick={()=>void selectEvent(cursor-1)}><ChevronLeft/></button><input aria-label="Posizione replay" type="range" min="0" max={Math.max(0,events.length-1)} value={cursor} onChange={e=>void selectEvent(Number(e.target.value))}/><button className="icon-button" disabled={cursor>=events.length-1} onClick={()=>void selectEvent(cursor+1)}><ChevronRight/></button><b>{events.length?cursor+1:0} / {events.length}</b></div><div className="replay-grid"><div className="event-list">{events.map((e,i)=><button key={i} onClick={()=>void selectEvent(i)} className={cursor===i?'active':''}><span className="event-index">{String(i+1).padStart(3,'0')}</span><b>{String(e.kind||e.type||'EVENT')}</b><span>{typeof e.timestamp==='number'?fmt(e.timestamp,2):''}</span></button>)}</div><div className="event-inspector"><div className="section-label">EVENTO SELEZIONATO</div><pre>{events.length?pretty(events[cursor]):'Nessun evento. Distribuisci una mano per iniziare.'}</pre><div className="section-label">STATO RICOSTRUITO</div><pre>{replay?pretty(replay):'Seleziona un evento per ricostruire lo stato fino a questo punto.'}</pre></div></div></section></>}
 {tab==='experiments'&&<><section className="panel experiment-controls"><div><div className="section-label">CONFRONTO POLICIES</div><h2>Un esperimento ripetibile.</h2><p>Le strategie vengono valutate sulle regole configurate. Metodo e intervalli sono parte del risultato.</p></div><label>Round<input type="number" min="10" max="10000" value={rounds} onChange={e=>setRounds(Number(e.target.value))}/></label><label>Seed<input type="number" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><label className="checkbox-label"><input type="checkbox" checked={withComposition} onChange={e=>setWithComposition(e.target.checked)}/>Composizione (più lenta)</label><button className="button primary" disabled={busy||!online} onClick={runExperiment}>{busy?<LoaderCircle size={16} className="spin"/>:<Play size={16}/>}Esegui</button></section>{experiment?<><ExperimentSummary result={experiment}/><section className="panel experiment-result"><div className="panel-header"><h2><BarChart3 size={17}/>Risultati misurati</h2><button className="button secondary" onClick={()=>download('experiment-'+seed+'.json',experiment)}><Download size={15}/>Esporta JSON</button></div><details className="raw-experiment"><summary>Esamina il report completo e i campioni</summary><pre>{pretty(experiment)}</pre></details></section></>:<section className="panel"><Empty><FlaskConical size={35}/><strong>I risultati appariranno qui.</strong><span>Nessun numero dimostrativo: ogni risultato arriva da un esperimento eseguito.</span></Empty></section>}</>}
 {tab==='rules'&&<><section className="panel rule-panel"><div className="panel-header"><h2>Regolamento & riproducibilità</h2><Badge>SI APPLICA A UNA NUOVA SESSIONE</Badge></div><div className="rule-grid"><label>Mazzi<select aria-label="Mazzi" value={rules.decks} onChange={e=>patchRule('decks',Number(e.target.value))}>{[1,2,4,6,8].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Dealer soft 17<select aria-label="Dealer soft 17" value={rules.hit_soft17?'H17':'S17'} onChange={e=>patchRule('hit_soft17',e.target.value==='H17')}><option>S17</option><option>H17</option></select></label><label>Blackjack payout<select aria-label="Blackjack payout" value={rules.blackjack_payout} onChange={e=>patchRule('blackjack_payout',Number(e.target.value))}><option value="1.5">3 : 2</option><option value="1.2">6 : 5</option></select></label><label>Double<select aria-label="Double" value={rules.double_rule} onChange={e=>patchRule('double_rule',e.target.value)}><option value="any">Qualsiasi due carte</option><option value="9-11">9–11</option><option value="10-11">10–11</option><option value="none">Nessun double</option></select></label><label>Surrender<select aria-label="Surrender" value={rules.surrender} onChange={e=>patchRule('surrender',e.target.value)}><option value="none">Nessuna</option><option value="late">Late surrender</option><option value="early">Early surrender</option></select></label><label>Perdita ENHC<select aria-label="Perdita ENHC" value={rules.enhc_loss} onChange={e=>patchRule('enhc_loss',e.target.value)}><option value="all">Tutte le puntate</option><option value="original">Solo puntata iniziale (OBO)</option></select></label><label>Massimo mani split<input type="number" min="1" max="8" value={rules.max_split_hands} onChange={e=>patchRule('max_split_hands',Number(e.target.value))}/></label><label>Penetrazione {fmt(rules.penetration*100,0)}%<input type="range" min=".1" max=".95" step=".05" value={rules.penetration} onChange={e=>patchRule('penetration',Number(e.target.value))}/></label><label>Seed<input type="number" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label></div><div className="rule-toggles">{([['dealer_peek','Dealer peek'],['enhc','European no-hole-card'],['double_after_split','Double after split'],['resplit','Resplit'],['resplit_aces','Resplit aces'],['hit_split_aces','Hit split aces']] as [keyof Rules,string][]).map(([k,l])=><label key={k}><input type="checkbox" checked={Boolean(rules[k])} onChange={e=>{patchRule(k,e.target.checked);if(k==='enhc'&&e.target.checked)patchRule('dealer_peek',false)}}/><span>{l}</span></label>)}</div><div className="rule-footer"><span>Le modifiche non cambiano una mano già distribuita.</span><button className="button primary" disabled={busy||!online} onClick={reset}><Check size={16}/>Applica e crea sessione</button></div></section></>}
 {tab==='poker'&&<PokerLab connected={online}/>}
 {tab==='roadmap'&&<section className="panel roadmap-panel"><div className="panel-header"><h2>Tutti i requisiti, una prova alla volta</h2><Badge>OBIETTIVO COMPLETO</Badge></div><div className="roadmap-summary">Motore · Solver · Vision · Tracking · Replay · Benchmark · Riferimenti · Desktop</div>{roadmap?.requirements?<div className="requirements">{roadmap.requirements.map((r:any)=><div key={r.id}><span className="milestone">{r.milestone}</span><div><b>{r.description}</b><small>{r.evidence}</small></div><Badge kind={r.status==='verified'?'green':'neutral'}>{r.status==='verified'?'Verificato':r.status==='partial'?'Parziale':'Da verificare'}</Badge></div>)}</div>:<Empty>Caricamento della matrice dei requisiti…</Empty>}</section>}
 <footer><span><Spade size={13}/>BLACKJACK VISION LAB</span><span>Matematica riproducibile. Stato osservabile. Prove ispezionabili.</span><span>RESEARCH / LOCAL</span></footer>
 <p className="global-disclaimer">Analysis and education only. Not financial advice. No system guarantees a winning outcome.</p></main></div>);
}
