export type Language='en'|'it';
/** English is the product default, independently of the browser locale. */
let language:Language='en';
try{if(localStorage.getItem('bjlab.language')==='it')language='it'}catch{}
export const getLanguage=()=>language;
export function setLanguage(value:Language){language=value;try{localStorage.setItem('bjlab.language',value)}catch{};if(typeof document!=='undefined')document.documentElement.lang=value;if(typeof window!=='undefined')window.dispatchEvent(new Event('bjlab:language'))}
const messages:Record<string,string>={
 'Tavolo & decisioni':'Table & decisions','Sistemi di conteggio':'Counting systems','Replay & eventi':'Replay & events','Esperimenti':'Experiments','Regolamento':'Rules','Roadmap completa':'Full roadmap',
 'Ogni carta, una prova.':'Every card, a piece of evidence.','Esplora il gioco. Confronta le decisioni. Ricostruisci il perché.':'Explore the game. Compare decisions. Understand the reasoning.',
 'La stessa shoe, più sistemi.':'One shoe, multiple systems.','Confronta conteggi e tag sugli stessi eventi osservati.':'Compare counts and tags on the same observed events.',
 'Dai pixel allo stato.':'From pixels to state.','Riconoscimento e tracking sul nostro simulatore controllato.':'Recognition and tracking on our controlled simulator.',
 'Il gioco, ricostruibile.':'A game you can reconstruct.','Ispeziona ogni evento e torna al punto in cui lo stato è cambiato.':'Inspect each event and return to any state transition.',
 'Le idee incontrano i numeri.':'Ideas meet evidence.','Esperimenti riproducibili con seed, regole e incertezza dichiarati.':'Reproducible experiments with explicit seeds, rules and uncertainty.',
 'Le regole cambiano il gioco.':'Rules change the game.','Configura un regolamento esplicito per il simulatore e il solver.':'Configure explicit rules for the simulator and solver.',
 'Un laboratorio completo.':'A complete laboratory.','Tutti i requisiti integrati, con evidenze e stato di verifica.':'Integrated requirements with evidence and verification status.',
 'Carta':'Hit','Stai':'Stand','Raddoppia':'Double','Dividi':'Split','Resa':'Surrender','Assicurazione':'Insurance','Rifiuta assicurazione':'Decline insurance','Continua':'Continue','Distribuisci':'Deal','Carta coperta':'Face-down card','Coperta':'Face down',
 'IL LABORATORIO':'THE LABORATORY','LABORATORIO':'LABORATORY','Ambiente di ricerca':'Research environment','Simulatore controllato':'Controlled simulator','Backend connesso':'Backend connected','Connessione…':'Connecting…','Backend non raggiungibile':'Backend unavailable','OSSERVA · CALCOLA · VERIFICA':'OBSERVE · CALCULATE · VERIFY','Nuova sessione':'New session',
 'Aspetto del simulatore':'Simulator appearance','Design carte':'Card design','Classico':'Classic','Essenziale':'Minimal','Velocità distribuzione':'Deal speed','Istantanea':'Instant','Rapida':'Fast','Lenta':'Slow','Gli intervalli cambiano l’animazione delle carte; il seed mantiene lo stesso gioco.':'Timing changes the card animation; the seed preserves the same game.',
 'Backend locale non connesso':'Local backend disconnected','Per usare questa pagina esegui run.ps1 nella cartella dei sorgenti e tienilo aperto. L’app desktop avvia il proprio backend quando la apri.':'Run run.ps1 from the source folder and keep it open. The desktop app starts its backend when opened.','Riconnetti':'Reconnect','Operazione non completata':'Operation not completed',
 'Il backend locale non risponde. Per questa pagina avvia run.ps1 dalla cartella dei sorgenti, oppure apri l’app desktop.':'The local backend is not responding. Start run.ps1 from the source folder, or open the desktop app.','Risposta del backend non valida. Riprova la connessione.':'Invalid backend response. Reconnect and try again.','Analisi non disponibile.':'Analysis unavailable.','Il file deve contenere una lista di eventi.':'The file must contain a list of events.',
 ' mazzi · ':' decks · ',' carte osservate':' observed cards','In attesa':'Waiting','Hi-Lo · eventi esposti':'Hi-Lo · exposed events',' mazzi fisici rimasti':' physical decks remaining','Normalizzato ai mazzi rimasti':'Normalized by remaining decks','RISULTATO SESSIONE':'SESSION RESULT','Round ':'Round ',' · unità di puntata':' · wager units','Nessuna mano giocata':'No hands played',
 'Simulatore':'Simulator','Turno giocatore':'Player turn','Mano conclusa':'Hand complete','Resa anticipata':'Early surrender','Pronto':'Ready','BANCO':'DEALER','MANO':'HAND','Profitto ':'Profit ','Puntata ':'Wager ','Puntata':'Wager','Il tuo prossimo esperimento':'Your next experiment','inizia con una mano.':'starts with a hand.','unità':'units',
 'Decisioni & EV':'Decisions & EV','Budget solver':'Solver budget','Ricalcola':'Recalculate','Calcolo degli EV':'Calculating EV','Regole e carte osservabili della mano corrente.':'Rules and observable cards of the current hand.','SOLUZIONE ESATTA':'EXACT SOLUTION','ANALISI · PRECISIONE DICHIARATA':'ANALYSIS · EXPLICIT PRECISION','Analisi parziale':'Partial analysis','Solver matematico':'Mathematical solver','EV condizionato alle informazioni osservate.':'EV conditional on observed information.','Consultare metodo e note per il livello di precisione.':'See method and notes for the precision level.','Esperimento concluso':'Experiment complete','Una decisione alla volta':'One decision at a time','Gli EV vengono calcolati quando è il turno del giocatore.':'EV is calculated during the player turn.','CONFRONTO STRATEGIE':'STRATEGY COMPARISON','Composizione':'Composition','Non calcolata':'Not calculated',
 'Pool non osservato':'Unobserved pool','Per valore · include carte nascoste':'By value · includes hidden cards','Stato dello shoe':'Shoe state','Fonte dello stato':'State source','Simulatore nativo':'Native simulator','Carte fisiche rimaste':'Physical cards remaining','Carte non esposte':'Unexposed cards','Penetrazione':'Penetration','Verifica attraverso i pixel':'Verify through pixels',
 'Tema':'Theme','Verde':'Green','Blu':'Navy','Bordeaux':'Burgundy','Sovrapposizione':'Overlap','Analizza frame':'Analyze image','Carica immagine':'Upload image','Frame controllato':'Controlled image','Frame del simulatore per riconoscimento carte':'Simulator image for card recognition','Nessuna sessione':'No session','Le etichette del simulatore restano separate dal detector. Il frame contiene soltanto le carte esposte.':'Simulator labels remain separate from the detector. The image contains only exposed cards.','Percezione & tracking':'Perception & tracking','Stato ricostruito e gate':'Reconstructed state and integrity gate','Esporta risultato':'Export result','Osservazioni prima delle decisioni':'Observations before decisions','Avvia l\'analisi per vedere detections, eventi e integrità dello stato.':'Start analysis to inspect detections, events and state integrity.',
 'Sessione JSON':'Session JSON','Eventi CSV':'Events CSV','Importa replay':'Import replay','eventi disponibili':'available events','Posizione replay':'Replay position','EVENTO SELEZIONATO':'SELECTED EVENT','STATO RICOSTRUITO':'RECONSTRUCTED STATE','Nessun evento. Distribuisci una mano per iniziare.':'No events. Deal a hand to get started.','Seleziona un evento per ricostruire lo stato fino a questo punto.':'Select an event to reconstruct the state up to that point.',
 'CONFRONTO POLICIES':'POLICY COMPARISON','Un esperimento ripetibile.':'A reproducible experiment.','Le strategie vengono valutate sulle regole configurate. Metodo e intervalli sono parte del risultato.':'Strategies are evaluated under configured rules. Method and intervals are part of the result.','Composizione (più lenta)':'Composition (slower)','Esegui':'Run','Risultati misurati':'Measured results','Esporta JSON':'Export JSON','Esamina il report completo e i campioni':'Inspect the full report and samples','I risultati appariranno qui.':'Results will appear here.','Nessun numero dimostrativo: ogni risultato arriva da un esperimento eseguito.':'Each result comes from an executed experiment.',
 'Regolamento & riproducibilità':'Rules & reproducibility','SI APPLICA A UNA NUOVA SESSIONE':'APPLIES TO A NEW SESSION','Mazzi':'Decks','Qualsiasi due carte':'Any two cards','Nessun double':'No double','Nessuna':'None','Perdita ENHC':'ENHC loss','Tutte le puntate':'All wagers','Solo puntata iniziale (OBO)':'Original bet only (OBO)','Massimo mani split':'Maximum split hands','Le modifiche non cambiano una mano già distribuita.':'Changes do not alter a hand already dealt.','Applica e crea sessione':'Apply and create session',
 'Tutti i requisiti, una prova alla volta':'Every requirement, backed by evidence','OBIETTIVO COMPLETO':'PROJECT REQUIREMENTS','Motore · Solver · Vision · Tracking · Replay · Benchmark · Riferimenti · Desktop':'Engine · Solver · Vision · Tracking · Replay · Benchmarks · References · Desktop','Verificato':'Verified','Parziale':'Partial','Da verificare':'To verify','Caricamento della matrice dei requisiti…':'Loading requirements matrix…','Matematica riproducibile. Stato osservabile. Prove ispezionabili.':'Reproducible mathematics. Observable state. Inspectable evidence.',
 'Sistemi sulla stessa sequenza osservata':'Systems on the same observed sequence','Esporta':'Export','carte esposte nello shoe corrente. Le carte coperte entrano nel conteggio quando vengono rivelate.':'exposed cards in the current shoe. Hidden cards enter the count when revealed.','Arrotondamento TC':'True-count rounding','Troncamento':'Truncate','Intero più vicino':'Nearest integer','Nessuno':'None','Sistema':'System','TC arrotondato':'Rounded TC','Normalizzazione':'Normalization','Mazzi rimasti':'Remaining decks','Il denominatore usa le carte fisiche rimaste dichiarate dal simulatore. Nella percezione questa quantità deve essere stimata separatamente.':'The denominator uses physical remaining cards declared by the simulator. Perception estimates this quantity separately.','Definisci un sistema personalizzato':'Define a custom counting system','Nome':'Name','Sistema bilanciato':'Balanced system','Valida e calcola':'Validate and calculate','I tag vengono validati rispetto alla composizione di un mazzo. Il risultato usa gli stessi eventi esposti del confronto.':'Tags are validated against deck composition. The result uses the same exposed events as the comparison.','Il mio sistema':'My counting system','Servono dieci tag numerici, da Asso a 10, separati da virgole.':'Enter ten numeric tags from Ace through ten, separated by commas.',
 'Stima del numero di mazzi':'Deck-count estimate','Numero di mazzi':'Number of decks',' · esito del clip':' · clip outcome','KNOWN · DICHIARATO':'KNOWN · DECLARED','INFERRED · INCERTO':'INFERRED · UNCERTAIN',' mazzi':' decks','mazzi':'decks','Numero non determinato':'Number undetermined','Sessione configurata':'Configured session','Dichiarazione per l’immagine':'Declared for the image','Dichiarazione per il video':'Declared for the video','Carte confermate dal tracker':'Cards confirmed by the tracker','Il valore proviene dalla configurazione dichiarata.':'The value comes from declared configuration.','La distribuzione deriva dalle carte confermate; il massimo del posteriore non rende noto il numero di mazzi. Il solver resta bloccato finché manca un inventario affidabile.':'The distribution comes from confirmed cards; the posterior maximum does not establish the deck count. Analysis is gated until inventory is reliable.','Osservazioni:':'Observations:','Evidenza incompatibile con i candidati: revisione necessaria.':'Evidence conflicts with the candidates; review required.','Assunzioni della stima':'Estimation assumptions',
 'Replay dei frame video':'Video image replay','Replay dei frame':'Video replay','Clip di un singolo round · frame campionati':'Single-round clip · sampled video','Frame precedente':'Previous image','Frame successivo':'Next image','Posizione frame video':'Video position','Frame sorgente':'Source image','Frame video ':'Video image ','Bounding box del frame video':'Video detection boxes','Anteprima non inclusa nel report.':'Preview not included in the report.','Stato fino a questo frame':'State up to this image','Eventi fino a questo frame (':'Events up to this image (','Detections del frame':'Image detections',
 'EV misurato & incertezza':'Measured EV & uncertainty','Profitto netto medio per unità di puntata iniziale. Gli intervalli descrivono il campionamento fra batch indipendenti.':'Mean net profit per initial wager unit. Intervals describe sampling across independent batches.','Il budget di tempo è terminato: il report usa soltanto i round effettivamente completati.':'The time budget ended; the report uses completed rounds only.','IC 95%:':'95% CI:','non disponibile':'unavailable','decisioni con fallback':'fallback decisions','DIFFERENZE TRA POLICIES · BATCH ABBINATI':'POLICY DIFFERENCES · PAIRED BATCHES','· IC 95%':'· 95% CI',
 'Non misurato':'Not measured','Non misurati':'Not measured','Bounding box delle carte riconosciute':'Recognized card detection boxes','Metriche della percezione':'Perception metrics','Misure della pipeline':'Pipeline measurements','Video locale':'Local video','Immagine importata':'Uploaded image','Frame del simulatore':'Simulator image','Latenza pixel':'Pixel latency','completa':'complete','media':'mean','OCR metadati':'Metadata OCR','Frame distinti analizzati':'Distinct images analyzed','FPS dello stream':'Stream FPS','Frame persi':'Dropped images','Latenza frame p95':'p95 image latency','Frame decodificati':'Decoded images','Il throughput include decodifica ed elaborazione dei frame campionati.':'Throughput includes decoding and processing of sampled video images.','Una singola immagine viene confermata con ':'One still image is confirmed with ',' aggiornamenti del tracker. Il throughput è una misura di elaborazione, non una frequenza di acquisizione live.':' tracker updates. Throughput measures processing, not live capture frequency.',' frame saltati per campionamento.':' video images skipped by sampling.',
 'Calibrazione, video e stato osservato':'Calibration, video and observed state','Chiudi strumenti':'Close tools','Apri strumenti':'Open tools','EV dalla percezione':'EV from perception','Il gate verifica lo stato ricostruito prima del calcolo.':'The integrity gate checks reconstructed state before analysis.','Questo import è indipendente. Analizza il frame del simulatore o associa esplicitamente un’immagine alla sessione.':'This import is independent. Analyze the simulator image or explicitly attach an image to the session.','ANALISI BLOCCATA DAL GATE':'ANALYSIS GATED','RISULTATO DELLO STATO OSSERVATO':'OBSERVED-STATE RESULT','Esporta analisi':'Export analysis','Mazzi dichiarati per l’import':'Declared decks for import','Sconosciuti':'Unknown','Associa l’immagine al tracker della sessione attiva':'Attach the image to the active session tracker','La configurazione dichiarata non dimostra che lo shoe sia stato osservato dall’inizio. Importa clip di un singolo round.':'Declared configuration does not prove observation from the start of the shoe. Import single-round clips.','Normalizza un’immagine':'Normalize an image','Seleziona gli angoli in ordine: alto sinistra, alto destra, basso destra, basso sinistra. Le zone sono rettangoli [x, y, larghezza, altezza] sul frame 960 × 600.':'Select corners in order: top left, top right, bottom right, bottom left. Zones are [x, y, width, height] rectangles on the 960 × 600 image.','Immagine da calibrare':'Image to calibrate','Immagine: seleziona i quattro angoli del tavolo':'Image: select the four table corners','/ 4 angoli':'/ 4 corners','Azzera':'Reset','Zone di riconoscimento':'Recognition zones','Calibra e importa':'Calibrate and import','Seleziona un’immagine.':'Select an image.','Indica tutti i quattro angoli oppure azzera la selezione.':'Select all four corners or reset the selection.','Lettura del file non riuscita.':'Could not read the file.','Il video supera 64 MiB.':'The video exceeds 64 MiB.','Analizza un video locale':'Analyze a local video','La ricostruzione usa i frame decodificati. Il report distingue le carte stabili dalle osservazioni ambigue.':'Reconstruction uses decoded video. The report distinguishes stable cards from ambiguous observations.','Un frame ogni':'Sample every','Massimo frame':'Maximum images','Carica video':'Upload video','Correggi una carta osservata':'Correct an observed card','Usa l’identità logica riportata nello stato. La correzione viene aggiunta al registro con la tua motivazione.':'Use the logical identity shown in state. The correction and your reason are recorded in the journal.','ID logico':'Logical ID','Valore':'Rank','Seme':'Suit','Motivazione':'Reason','Motivazione della correzione':'Correction reason','Registra correzione':'Record correction',
 'Condivisione dello schermo':'Screen sharing','Osserva una finestra o lo schermo':'Observe a window or the screen','Condividi finestra o schermo':'Share window or screen','Scegli la sorgente…':'Choose a source…','Condivisione attiva':'Sharing active','In attesa della tua scelta':'Waiting for your selection','Nessuna sorgente condivisa':'No source shared','Ferma condivisione':'Stop sharing','Annulla':'Cancel','Anteprima della sorgente condivisa':'Shared-source preview','Acquisisci fotogramma':'Capture image','Attendi che l’anteprima sia pronta.':'Wait for the video preview to be ready.','Acquisizione del fotogramma non disponibile.':'Image capture unavailable.','Acquisizione del fotogramma non riuscita.':'Image capture failed.','Anteprima non avviata. Ferma e riprova la condivisione.':'Preview could not start. Stop and retry sharing.','Condivisione annullata o non autorizzata. Puoi riprovare e scegliere la finestra.':'Sharing cancelled or denied. Retry and select a window.','La sorgente non è acquisibile. Scegli un’altra finestra o carica uno screenshot.':'Cannot capture this source. Choose another window or upload an image.','Impossibile avviare la condivisione.':'Could not start sharing.','Questo browser non supporta la condivisione. Apri questa pagina in Chrome o Edge, oppure carica uno screenshot.':'This browser does not support sharing. Open this page in Chrome or Edge.',
 'Scegli tu la sorgente nel selettore del browser. L’anteprima resta locale. Acquisisci un fotogramma, seleziona il tavolo nell’immagine e premi «Calibra e importa» per analizzarlo.':'Choose the source in the browser picker. For continuous observation, use Live vision. This legacy tool imports individual images.',
 'Fotogramma pronto nella sezione «Normalizza un’immagine» qui sotto. La cattura non garantisce il riconoscimento di carte con grafica diversa da quella del laboratorio.':'Image ready under Normalize an image. Other card artwork requires separate validation.',
 'Usa Chrome o Edge su localhost. Nei browser integrati la condivisione può non essere disponibile; resta possibile caricare uno screenshot. Chiudendo gli strumenti o cambiando sezione la condivisione si ferma.':'Use Chrome or Edge on localhost. Integrated browsers may not support display capture. Closing these legacy tools stops their source.',
 'Language':'Lingua','Live vision':'Visione live','Watch the game. Follow every decision.':'Osserva la partita. Segui ogni decisione.','Continuous video, persistent card tracking and probability estimates.':'Video continuo, tracking persistente e stime delle probabilità.',
 'Share screen':'Condividi schermo','Stop video':'Ferma video','Run lab demo':'Avvia demo del laboratorio','Open simulator window':'Apri finestra simulatore','Floating advisor':'Consigliere flottante','Waiting for video':'In attesa del video','Video connected':'Video connesso','Start observing':'Avvia osservazione','Stop observing':'Ferma osservazione','Apply calibration':'Applica calibrazione','Clear corners':'Azzera angoli','Table calibration':'Calibrazione del tavolo','Selected corners':'Angoli selezionati','Observe from a new shoe':'Osserva da un nuovo shoe','Player turn (manual layout)':'Turno del giocatore (layout manuale)','Samples per action':'Campioni per azione','Video processing':'Elaborazione video','Observed cards':'Carte osservate','Running count':'Running count','True count':'True count','Win':'Vittoria','Push':'Parità','Loss':'Sconfitta','Estimated EV':'EV stimato','Recommended action':'Azione consigliata','Waiting for stable cards':'In attesa di carte stabili','Decision stale — waiting for fresh video':'Consiglio scaduto — attendo nuovo video','No source selected':'Nessuna sorgente selezionata','Lab video demo':'Demo video del laboratorio','Screen video':'Video dello schermo','Pause bot':'Ferma bot','Resume bot':'Riprendi bot','New shoe':'Nuovo shoe','Export observed events':'Esporta eventi osservati','Cards':'Carte','Dealer':'Banco','Player':'Giocatore','Probability estimates':'Stime delle probabilità','95% confidence interval':'Intervallo di confidenza al 95%','Simulated outcomes':'Esiti simulati','No positive EV detected':'Nessun EV positivo rilevato','Positive estimated EV':'EV stimato positivo','Waiting for a decision':'In attesa di una decisione','Fresh shoe declared':'Nuovo shoe dichiarato','Partial observed count':'Conteggio parziale osservato','No clear ranking':'Ordine delle azioni incerto','Close advisor':'Chiudi consigliere','Open in default browser':'Apri nel browser predefinito',
};
const liveItalian:Record<string,string>={
 'Opening advisor…':'Apertura del consigliere…','Floating live advisor':'Consigliere live flottante','Pop out advisor':'Apri consigliere in finestra',
 'Advisor is shown in this page. Use Chrome or Edge for a separate always-on-top window.':'Il consigliere è mostrato in questa pagina. Usa Chrome o Edge per una finestra separata sempre in primo piano.',
 'CONTINUOUS SCREEN VIDEO':'VIDEO CONTINUO DELLO SCHERMO','Share once. Follow the whole game.':'Condividi una volta. Segui tutta la partita.',
 'Choose a screen, window or browser tab. Observation continues automatically; no image capture button is needed.':'Scegli schermo, finestra o scheda del browser. L’osservazione prosegue automaticamente, senza acquisizioni manuali.',
 'Continuous shared video':'Video condiviso continuo','Live recognized cards':'Carte riconosciute in diretta','Give the lab a live video source.':'Fornisci al laboratorio una sorgente video live.',
 'Share your simulation, or run the lab demo to test video → recognition → tracking → advice.':'Condividi la tua simulazione oppure avvia la demo per provare video → riconoscimento → tracking → consiglio.',
 'Video paused':'Video in pausa','Selected corners:':'Angoli selezionati:','500 · fast':'500 · rapido','1,500 · balanced':'1.500 · bilanciato','5,000 · precise':'5.000 · preciso',
 'For a full screen, select the table corners: top left, top right, bottom right, bottom left. Keep its position fixed while observing.':'Per lo schermo completo seleziona gli angoli del tavolo: alto sinistra, alto destra, basso destra, basso sinistra. Mantieni la posizione fissa durante l’osservazione.',
 'Distinct observations':'Osservazioni distinte','Skipped while busy':'Saltate durante l’elaborazione',
 'Processing runs locally. The preview is video; the analysis samples it automatically with one upload in flight. Guidance expires when the video stops updating.':'L’elaborazione è locale. L’anteprima è video; l’analisi lo campiona automaticamente, con un solo invio alla volta. Il consiglio scade quando il video smette di aggiornarsi.',
 'Recognition scope and probability method':'Ambito del riconoscimento e metodo probabilistico',
 'The included detector is validated for lab card artwork. Other artwork needs a trained detector and a separate test. Counts cover only what the video has actually observed. Select a new shoe before relying on a full-shoe count.':'Il detector incluso è validato sulla grafica delle carte del laboratorio. Altre grafiche richiedono un detector addestrato e una verifica separata. Il conteggio copre ciò che il video ha osservato. Parti da un nuovo shoe per un conteggio completo.',
 'Win, push and loss describe net profit of the active hand, including any new splits. Existing other hands are excluded. EV estimates use finite-pool Monte Carlo with generated basic continuation; sampling intervals do not measure perception error.':'Vittoria, parità e sconfitta descrivono il profitto netto della mano attiva, inclusi nuovi split. Le altre mani già presenti sono escluse. Gli EV usano Monte Carlo su pool finito con continuazione basic generata; gli intervalli di campionamento non misurano l’errore percettivo.',
 'Display sharing needs Chrome or Edge on localhost.':'La condivisione richiede Chrome o Edge su localhost.','Observe → verify → decide':'Osserva → verifica → decidi','95% confidence interval:':'Intervallo di confidenza al 95%:',
 'simulated outcomes per action ·':'esiti simulati per azione ·','Monte Carlo estimate':'Stima Monte Carlo','Exact':'Esatto','Action':'Azione','Dealer blackjack:':'Blackjack del banco:','· Insurance EV:':'· EV assicurazione:',
 'Advice is hidden until new video arrives.':'Il consiglio resta nascosto fino a un nuovo video.','Select a video source to begin.':'Seleziona una sorgente video per iniziare.',
 'Need at least two player cards and exactly one visible dealer upcard.':'Servono almeno due carte del giocatore e una sola carta scoperta del banco.',
 'Waiting for a player decision in the video.':'In attesa di una decisione del giocatore nel video.',
 'Visible round context is changing; waiting for stable video evidence.':'Il contesto della mano sta cambiando; attendo evidenza video stabile.',
 'Some card-shaped regions could not be read.':'Alcune regioni con forma di carta non sono leggibili.','Active player cards are not fully visible.':'Le carte della mano attiva non sono tutte visibili.',
 'No readable legal player controls; calibrate the table or declare a manual player turn.':'Comandi del giocatore non leggibili: calibra il tavolo oppure dichiara il turno manuale.',
 'Select all four table corners before observing.':'Seleziona tutti i quattro angoli prima dell’osservazione.','Video processing failed.':'Elaborazione video non riuscita.',
 'Video processing timed out. Waiting for a fresh observation.':'Tempo di elaborazione scaduto. Attendo una nuova osservazione.','Video preview could not start. Stop and retry.':'Anteprima video non avviata. Ferma e riprova.',
 'The advisor popup was blocked. Allow popups for this local page.':'Il pop-up è stato bloccato. Consenti i pop-up per questa pagina locale.',
 'Opened the local app in your browser. Keep the desktop app open while sharing.':'Applicazione locale aperta nel browser. Tieni aperta l’app desktop durante la condivisione.',
 'Export observation':'Esporta osservazione','BLACKJACK VISION LAB / VIDEO SOURCE':'BLACKJACK VISION LAB / SORGENTE VIDEO','A table your live advisor can watch.':'Un tavolo che il consigliere live può osservare.',
 'Share this window from Live vision, select the four table corners, and play manually or start the bot. The advisor reads the visible video, including round labels and buttons.':'Condividi questa finestra da Visione live, seleziona i quattro angoli e gioca manualmente oppure avvia il bot. Il consigliere legge il video visibile, comprese etichette e pulsanti.',
 'Visible blackjack simulation table':'Tavolo visibile della simulazione blackjack','Starting simulator…':'Avvio del simulatore…','New session':'Nuova sessione','· Net profit':'· Profitto netto','units':'unità','player':'giocatore','settled':'conclusa','ready':'pronto','insurance':'assicurazione','early_surrender':'resa anticipata',
};

const versionOneItalian:Record<string,string>={
 'Tracked cards do not match the visible hand total. Waiting for fresh card evidence.':'Le carte tracciate non corrispondono al totale visibile. In attesa di una nuova lettura delle carte.',
 'Recognition supports lab cards and compatible classic green casino tables. Include printed corners, hand totals and English action buttons. The largest compatible table is located automatically. Counts cover observed cards; declare external shuffles explicitly. Unreadable or multiple active hands need confirmation.':'Il riconoscimento supporta le carte del laboratorio e i tavoli verdi classici compatibili. Includi gli angoli stampati, i totali delle mani e i pulsanti in inglese. Il tavolo compatibile più grande viene individuato automaticamente. Il conteggio riguarda le carte osservate: dichiara esplicitamente i rimescolamenti esterni. Le mani illeggibili o più mani attive richiedono conferma.',
 'Enter at least two player cards, for example 7 2.':'Inserisci almeno due carte del giocatore, ad esempio 7 2.',
 'Enter one dealer upcard, for example 6.':'Inserisci una carta scoperta del banco, ad esempio 6.',
 'Enter exactly one dealer upcard.':'Inserisci esattamente una carta scoperta del banco.',
 'The player total could not be verified. Enlarge the shared game window.':'Il totale del giocatore non è verificabile. Ingrandisci la finestra del gioco condivisa.',
 'The dealer upcard could not be read. Enlarge the shared game window.':'La carta scoperta del banco non è leggibile. Ingrandisci la finestra del gioco condivisa.',
 'The recognized cards do not match the visible hand total. Enlarge or recalibrate the table.':'Le carte riconosciute non corrispondono al totale visibile. Ingrandisci o ricalibra il tavolo.',
 'Several player hands are visible. Confirm the active hand manually.':'Sono visibili più mani del giocatore. Conferma manualmente la mano attiva.',
 'Ask before reusing saved settings':'Chiedi prima di riusare le impostazioni salvate',
 'NEW SESSION':'NUOVA SESSIONE','Start new session':'Avvia nuova sessione','The new session starts with a fresh simulated shoe. Match its rules before observing it.':'La nuova sessione parte con mazzi simulati nuovi. Verifica le regole prima di osservarla.','Double rule':'Regola del raddoppio','Maximum split hands':'Massimo di mani dopo split','Double after split':'Raddoppio dopo split','Resplit pairs':'Dividi ancora le coppie','Resplit aces':'Dividi ancora gli assi','Hit split aces':'Carta dopo split degli assi','European dealer blackjack loss':'Perdita su blackjack del banco europeo','All wagers':'Tutte le puntate','Original wager only (OBO)':'Solo puntata originale (OBO)',
 'Observed cards only':'Solo carte osservate','From declared fresh shoe':'Dai nuovi mazzi dichiarati','Perception lab':'Laboratorio visivo','Hand created by a split':'Mano creata da uno split','Hands in this round':'Mani in questo round','Observed cards (optional, includes current cards)':'Carte osservate (facoltativo, include le carte attuali)',
 'Programs & extensions':'Programmi ed estensioni','Image & manual advice':'Immagini e carte confermate','Basic strategy library':'Libreria strategia base','Quick guide':'Guida rapida','Configure':'Configura',
 'Set up the way you play.':'Configura il tuo laboratorio.','Essential programs, local models and optional helpers.':'Programmi essenziali, modelli locali e strumenti facoltativi.',
 'An image. A clearer decision.':'Un’immagine. Una decisione più chiara.','Paste, drop or confirm the cards you can see.':'Incolla, trascina o conferma le carte visibili.',
 'The strategy, at a glance.':'La strategia, a colpo d’occhio.','Hard totals, soft hands, pairs and every starting rank combination.':'Totali duri, mani soft, coppie e tutte le combinazioni iniziali.',
 'LIVE WORKSPACE':'AREA LIVE','One table. One clear decision.':'Un tavolo. Una decisione chiara.','+ Add table':'+ Aggiungi tavolo','Stop all sources':'Ferma tutte le sorgenti','Table name':'Nome tavolo','Game type':'Tipo di gioco','Blackjack':'Blackjack','Poker / other · monitor only':'Poker / altro · solo monitoraggio','Remove':'Rimuovi',
 'Each table has its own card history, rules and advisor. A shared display is selected once; calibrate a separate table region for each observer.':'Ogni tavolo ha una cronologia, regole e un consigliere indipendenti. Seleziona lo schermo una volta e calibra una regione distinta per ogni osservatore.',
 'NEW TABLE':'NUOVO TAVOLO','Use your saved configuration?':'Usare la configurazione salvata?','The new table starts with an empty observed history. Its count stays independent from the other tables.':'Il nuovo tavolo parte da una cronologia vuota. Il conteggio resta indipendente dagli altri tavoli.','Use these settings without asking again':'Usa queste impostazioni senza chiedere ancora','Add independent table':'Aggiungi tavolo indipendente',
 'TABLE CONFIGURATION':'CONFIGURAZIONE TAVOLO','A few rules. A useful starting point.':'Poche regole. Un punto di partenza utile.','Match the actual table. These settings determine legal actions and the strategy reference.':'Imposta le regole del tavolo effettivo. Determinano le azioni consentite e la strategia di riferimento.',
 'Saving starts a new observer history for this table. Declare a fresh shoe only when the decks have actually been reset.':'Salvare avvia una nuova cronologia per questo tavolo. Dichiara nuovi mazzi solo quando le carte sono state effettivamente rimescolate.',
 'Game mode':'Modalità di gioco','Standard blackjack':'Blackjack standard','Hit / stand only':'Solo carta / stai','Custom rules':'Regole personalizzate','Decks':'Mazzi','Dealer on soft 17':'Banco su soft 17','Stand (S17)':'Stai (S17)','Hit (H17)':'Carta (H17)','Dealer card procedure':'Procedura del banco','American peek':'Peek americano','European no-hole-card':'Europeo senza carta coperta','Blackjack payout':'Pagamento blackjack','Late surrender':'Resa tardiva','Early surrender':'Resa anticipata','Advanced rules':'Regole avanzate','Any two cards':'Qualsiasi coppia di carte','9–11 only':'Solo 9–11','10–11 only':'Solo 10–11','Disabled':'Disabilitato','Save configuration':'Salva configurazione','Cancel':'Annulla',
 'A “shoe” is the collection of cards dealt from the selected decks. Start observing before the first deal for a complete count.':'Lo “shoe” è l’insieme delle carte dei mazzi selezionati. Osserva dalla prima distribuzione per un conteggio completo.',
 'Configure your table':'Configura il tavolo','Select decks, dealer rules and permitted actions. Each table can have a different configuration.':'Seleziona mazzi, regole del banco e azioni consentite. Ogni tavolo può avere una configurazione diversa.','Choose a source':'Scegli una sorgente','Share a screen or use the simulator. You can also paste or drop an image. For a shared screen, select the four corners of each table.':'Condividi lo schermo o usa il simulatore. Puoi anche incollare o trascinare un’immagine. Seleziona i quattro angoli di ogni tavolo sullo schermo.',
 'Read the short answer':'Leggi il consiglio rapido','The action is shown first. Aces display their active value and alternative total. Counts update from confirmed exposed cards.':'L’azione appare per prima. Gli assi mostrano il valore attivo e il totale alternativo. I conteggi si aggiornano dalle carte esposte confermate.','Open the details when useful':'Apri i dettagli quando servono','Expand the advisor for basic strategy, EV, uncertainty and observed composition. The offline strategy library covers hard totals, soft totals, pairs and 550 starting combinations.':'Espandi il consigliere per strategia base, EV, incertezza e composizione osservata. La libreria locale comprende totali duri, soft, coppie e 550 combinazioni iniziali.',
 'Skip guide':'Salta guida','Start exploring':'Apri il laboratorio','Next':'Avanti','Video':'Video','Paste':'Incolla','Drop':'Trascina','Basic policy':'Strategia base','Count':'Conteggio','20 · hard total':'20 · totale duro',
 'NEXT ACTION':'PROSSIMA AZIONE','TABLE STATUS':'STATO DEL TAVOLO','Composition estimate':'Stima composizione','Basic strategy':'Strategia base','Video evidence':'Evidenza video','Connect a source':'Collega una sorgente','Refresh the video':'Aggiorna il video','Check the table':'Verifica il tavolo','Hand complete':'Mano conclusa','Soft total':'Totale soft','Hard total':'Totale duro','Positive outcome':'Esito positivo','Negative outcome':'Esito negativo','Running count':'Conteggio corrente','Observed':'Osservate','Why this action & advanced details':'Motivo del consiglio e dettagli avanzati','Hi-Lo reference':'Riferimento Hi-Lo','Not available':'Non disponibile','Estimated EV per initial wager':'EV stimato per puntata iniziale','EV ranking separated':'Ordine EV distinto','EV intervals overlap; basic strategy remains the primary recommendation.':'Gli intervalli EV si sovrappongono: il consiglio principale resta la strategia base.',
 'Refresh the source before acting.':'Aggiorna la sorgente prima di agire.','Wait for the next deal.':'Attendi la prossima distribuzione.','Share a table, run the demo, or confirm cards manually.':'Condividi un tavolo, avvia la demo o conferma le carte.',
 'Analysis and education only. Not financial advice. No guaranteed outcomes.':'Solo analisi e formazione. Non sono consigli finanziari. Nessun esito garantito.','Analysis and education only. Not financial advice. No system guarantees a winning outcome.':'Solo analisi e formazione. Non sono consigli finanziari. Nessun sistema garantisce una vincita.',
 'ONE IMAGE · ONE DECISION':'UN’IMMAGINE · UNA DECISIONE','Paste. Drop. Understand the hand.':'Incolla. Trascina. Comprendi la mano.','Ctrl + V pastes an image anywhere in this view. A still image gives current-hand advice; it cannot reconstruct earlier cards.':'Ctrl + V incolla un’immagine in questa vista. Una singola immagine permette di analizzare la mano attuale, senza ricostruire le carte precedenti.','Choose an image':'Scegli un’immagine','Reading image…':'Lettura immagine…','Confirm or enter cards':'Conferma o inserisci le carte','Player cards':'Carte giocatore','Dealer upcard':'Carta scoperta banco','Confirm player turn & analyze':'Conferma il turno e analizza','For unsupported artwork, enter the visible player cards and dealer upcard. Confirm that it is your turn. A, 2–10, J, Q and K are accepted.':'Per grafiche non supportate, inserisci le carte visibili del giocatore e del banco. Conferma che sia il tuo turno. Sono accettati A, 2–10, J, Q e K.',
 'Basic strategy · offline library':'Strategia base · libreria locale','Hard totals':'Totali duri','Soft totals':'Totali soft','Pairs':'Coppie','Naturals':'Blackjack naturali','All combinations':'Tutte le combinazioni','Export library':'Esporta libreria','Search combinations':'Cerca combinazioni','A complete rule-generated reference for hard totals, soft totals, pairs and every starting rank combination. Aces may count as 1 or 11. The best usable value is selected automatically.':'Riferimento generato dalle regole per totali duri, soft, coppie e ogni combinazione iniziale. Gli assi valgono 1 o 11: viene scelto automaticamente il valore migliore utilizzabile.',
 'Independent-draw reference; finite deck composition and count deviations are compared separately. Single-deck composition can differ. These calculations run locally and need no online chart lookup.':'Riferimento con estrazioni indipendenti; composizione finita e deviazioni di conteggio sono confrontate separatamente. Con un solo mazzo la composizione può cambiare il risultato. I calcoli sono locali e non richiedono ricerche online.',
 'ESSENTIAL PROGRAMS':'PROGRAMMI ESSENZIALI','A small core. Optional extras.':'Un nucleo semplice. Strumenti facoltativi.','OPTIONAL · CLEF':'FACOLTATIVO · CLEF','Local scene classification':'Classificazione locale della scena','Checking…':'Verifica…','Check local Clef runtime':'Verifica Clef locale','Installation & hardware notes':'Installazione e requisiti hardware','OPTIONAL · BROWSER EXTENSION':'FACOLTATIVO · ESTENSIONE BROWSER','A quick tab image':'Un’immagine rapida della scheda','Extension source & setup':'Sorgenti e configurazione estensione','Optional Clef scene check':'Verifica scena con Clef facoltativa','Classifying…':'Classificazione…','Classify this image with Clef':'Classifica questa immagine con Clef','Visual monitor':'Monitoraggio visivo',
};
const reliabilityItalian:Record<string,string>={
"Understand the hand. Measure equity.":"Comprendi la mano. Misura l’equity.","Texas Hold’em with ranks, suits and explicit opponent ranges.":"Texas Hold’em con valori, semi e range avversari espliciti.","Drag a rectangle around your two hole cards.":"Trascina un rettangolo intorno alle tue due carte.","Drag a rectangle around the community-card area.":"Trascina un rettangolo intorno alle carte comuni.","Frames monitored:":"Fotogrammi monitorati:","· Card analyses:":"· Analisi delle carte:","· Hole:":"· Carte personali:","· Board:":"· Board:","High card":"Carta alta","One pair":"Coppia","Two pair":"Doppia coppia","Three of a kind":"Tris","Straight":"Scala","Flush":"Colore","Full house":"Full","Four of a kind":"Poker","Straight flush":"Scala colore","opponent(s)":"avversario/i","95% sampling interval:":"Intervallo di campionamento 95%:","Explicit equally weighted combinations where supplied; otherwise uniformly random unknown hands.":"Combinazioni esplicite con pari peso quando inserite; altrimenti mani sconosciute casuali uniformi.","hole":"carte personali",
"Independent Clef verification (experimental)":"Verifica indipendente con Clef (sperimentale)","Independent Clef image verification":"Verifica indipendente dell’immagine con Clef","Verify this table with Clef":"Verifica questo tavolo con Clef","Stop & save video":"Ferma e salva video","Texas Hold’em · calibrated vision":"Texas Hold’em · visione calibrata","Optionally save the selected video and observed events on this computer. Recording is off by default. No video is sent to an external service.":"Puoi salvare il video selezionato e gli eventi su questo computer. La registrazione è disattivata all’avvio. Nessun video viene inviato a servizi esterni.",
 "Texas Hold’em lab": "Laboratorio Texas Hold’em",
 "Read the hand. Compare the possibilities.": "Leggi la mano. Confronta le possibilità.",
 "CALIBRATED POKER VISION · EXPERIMENTAL": "VISIONE POKER CALIBRATA · SPERIMENTALE",
 "Select your two hole cards and the community-card area. The same regions stay active throughout the video. Unsupported suits stay unknown.": "Seleziona le tue due carte e l’area delle carte comuni. Le regioni restano attive durante il video. I semi non riconosciuti rimangono sconosciuti.",
 "Share poker screen": "Condividi schermo poker",
 "Choose poker image": "Scegli immagine poker",
 "Stop poker video": "Ferma video poker",
 "Poker shared video": "Video poker condiviso",
 "Poker table for region calibration": "Tavolo poker per calibrare le regioni",
 "Select hole cards": "Seleziona carte personali",
 "Select community cards": "Seleziona carte comuni",
 "Analyze poker source": "Analizza sorgente poker",
 "Pause poker analysis": "Pausa analisi poker",
 "Select both your hole-card region and the community-card region.": "Seleziona sia la regione delle carte personali sia quella delle carte comuni.",
 "Both card regions are configured.": "Entrambe le regioni sono configurate.",
 "Empty board is confirmed as preflop": "Il board vuoto è confermato come preflop",
 "Choose a PNG, JPEG or WebP image below 8 MiB.": "Scegli un’immagine PNG, JPEG o WebP inferiore a 8 MiB.",
 "Cards confirmed": "Carte confermate",
 "Check the poker table": "Verifica il tavolo poker",
 "Export poker events": "Esporta eventi poker",
 "Calibrated card recognition and showdown equity only. Pot size, betting turn, stacks, rake and side pots require explicit input. A complete poker action advisor is a separate roadmap item.": "Riconoscimento calibrato delle carte ed equity allo showdown. Piatto, turno di puntata, stack, rake e piatti laterali richiedono informazioni esplicite. Il consigliere completo per le azioni poker è una voce separata della roadmap.",
 "TEXAS HOLD’EM · SHOWDOWN EQUITY": "TEXAS HOLD’EM · EQUITY ALLO SHOWDOWN",
 "Your two cards": "Le tue due carte",
 "Board: flop, turn or river": "Board: flop, turn o river",
 "Opponents": "Avversari",
 "Pot before your call": "Piatto prima del tuo call",
 "Cost to call": "Costo del call",
 "Samples": "Campioni",
 "Enter ranks and suits: AS, 10H, K♦. Choose the opponents and include known dead cards. Hidden cards are sampled, never inferred.": "Inserisci valori e semi: AS, 10H, K♦. Seleziona gli avversari e includi le carte note escluse. Le carte nascoste vengono campionate, senza inventarle.",
 "Known dead cards and opponent ranges": "Carte note escluse e range avversari",
 "Known dead cards": "Carte note escluse",
 "Optional explicit ranges (JSON)": "Range espliciti facoltativi (JSON)",
 "One list per opponent. Each two-card combination has equal weight. Use null for a uniformly random opponent. Known-card blockers are removed automatically.": "Una lista per avversario. Ogni combinazione di due carte ha lo stesso peso. Usa null per un avversario casuale uniforme. Le combinazioni incompatibili con le carte note vengono escluse.",
 "Calculating equity…": "Calcolo equity…",
 "Calculate equity": "Calcola equity",
 "EQUITY · EXPLICIT ASSUMPTIONS": "EQUITY · IPOTESI ESPLICITE",
 "Configure the hand": "Configura la mano",
 "Win": "Vittoria",
 "Tie": "Parità",
 "Loss": "Sconfitta",
 "Pot odds": "Pot odds",
 "Showdown call EV": "EV del call allo showdown",
 "Equity is your expected share of the pot at showdown. It is not an optimal betting decision. Future betting, rake and side pots need a separate model.": "L’equity è la quota attesa del piatto allo showdown. Non determina una puntata ottimale. Puntate future, rake e piatti laterali richiedono un modello separato.",
 "Clef is checking the captured table…": "Clef sta verificando il tavolo acquisito…",
 "Clef agrees with the visible hand": "Clef concorda con la mano visibile",
 "Visual disagreement — confirm the cards": "Letture visive discordanti: conferma le carte",
 "Clef unavailable": "Clef non disponibile",
 "Clef verification inconclusive": "Verifica Clef inconclusiva",
 "Independent Clef verification": "Verifica indipendente con Clef",
 "Experimental second check. Model scores are not recognition accuracy or outcome probabilities.": "Seconda verifica sperimentale. I punteggi del modello non misurano l’accuratezza né la probabilità degli esiti.",
 "Inspect visual evidence": "Esamina evidenza visiva",
 "Start the separate local Clef runtime on port 9051.": "Avvia Clef locale separatamente sulla porta 9051.",
 "Verify this image independently with Clef": "Verifica questa immagine indipendentemente con Clef",
 "Verifying…": "Verifica…",
 "Independent visual verification": "Verifica visiva indipendente",
 "Local video replay": "Replay video locale",
 "Record video locally": "Registra video localmente",
 "Stop and save video": "Ferma e salva video",
 "Nothing is recorded by default. The selected video is saved locally as WebM, with timing metadata; maximum 200 MiB.": "La registrazione è disattivata all’avvio. Il video selezionato viene salvato localmente in WebM con i tempi; massimo 200 MiB.",
 "Frames monitored": "Fotogrammi monitorati",
 "Card analyses": "Analisi delle carte",
 "Capture continuity is incomplete. Count estimates are unavailable.": "La continuità della cattura è incompleta. Le stime del conteggio non sono disponibili.",
 "Unavailable · incomplete history": "Non disponibile · storia incompleta",
 "Observation history is incomplete. Declare a new shoe to restore the count.": "La storia osservata è incompleta. Dichiara un nuovo shoe per ripristinare il conteggio.",
 "EV analysis":"Analisi EV","In progress":"In corso","Waiting for an analysis slot":"In attesa di disponibilità",
 "Complete":"Completata","Budget reached":"Tempo disponibile esaurito",
 "Basic strategy remains available while estimates run.":"La strategia base resta disponibile durante il calcolo delle stime.",
 "Observation began mid-shoe or its initial history is unknown. True count and physical inventory are unavailable.":"L’osservazione è iniziata a shoe avviato o la storia iniziale è sconosciuta. True count e inventario fisico non sono disponibili."
};
// Legacy labels use Italian keys. New features use English keys; both translate.
const primary=new Map<string,string>(),secondary=new Map<string,string>();
let englishKeys=false;
for(const [key,value] of Object.entries(messages)){
 if(key==='Language')englishKeys=true;
 const it=(englishKeys?value:key).trim(),en=(englishKeys?key:value).trim();
 primary.set(it,en);if(!secondary.has(en))secondary.set(en,it);
}
const visionItalian:Record<string,string>={"Always on top": "Sempre in primo piano", "Live advisor": "Advisor live", "Close": "Chiudi", "Recognition profile": "Profilo di riconoscimento", "Automatic · current baseline": "Automatico · baseline attuale", "Calibrated corners · research": "Angoli calibrati · ricerca", "Region": "Regione", "Table": "Tavolo", "Dealer cards": "Carte del banco", "Player cards": "Carte del giocatore", "Controls (diagnostic)": "Controlli (diagnostica)", "Drag a region on the video": "Trascina una regione sul video", "Apply native regions": "Applica le regioni native", "Save private vision diagnostic": "Salva diagnostica vision privata", "Normalized regions": "Regioni normalizzate", "VISION EXPERIMENT FUNNEL": "FUNNEL DEGLI ESPERIMENTI VISION", "Evidence before promotion.": "Le prove prima della promozione.", "Export experiment matrix": "Esporta matrice esperimenti", "Executed development comparison": "Confronto di sviluppo eseguito", "Stage": "Fase", "Candidate": "Candidato", "Finding / next proof": "Risultato / prossima verifica", "Correct zone / ranks": "Zone / ranghi corretti", "Suit reads": "Semi letti", "Offline p95": "p95 offline", "proposed": "proposto", "available": "disponibile", "executed": "eseguito", "rejected": "bocciato", "Drag the native title bar to another monitor. This window views one observer; closing it keeps capture active.": "Trascina la barra nativa su un altro monitor. Questa finestra mostra un solo observer; chiuderla mantiene attiva la cattura."};
for(const [en,it] of Object.entries({...visionItalian,...liveItalian,...versionOneItalian,...reliabilityItalian})){primary.set(it,en);secondary.set(en,it)}
export function t(text:string):string{
 const raw=text.trim();
 let translated=language==='en'?(primary.get(raw)||raw):(secondary.get(raw)||raw);
 const dynamic: [RegExp,string,string][]=[
  [/^(\d+) mazzi · (\d+) carte osservate$/,'$1 decks · $2 observed cards','$1 mazzi · $2 carte osservate'],
  [/^([\d.]+) mazzi fisici rimasti$/,'$1 physical decks remaining','$1 mazzi fisici rimasti'],
  [/^Round (\d+) · unità di puntata$/,'Round $1 · wager units','Round $1 · unità di puntata'],
  [/^Profitto ([\d.+-]+)$/,'Profit $1','Profitto $1'],
  [/^Puntata ([\d.+-]+)$/,'Wager $1','Puntata $1'],
  [/^(\d+) mazzi$/,'$1 decks','$1 mazzi'],
  [/^Frame video (\d+)$/,'Video image $1','Frame video $1'],
  [/^Eventi fino a questo frame \((\d+)\)$/,'Events up to this image ($1)','Eventi fino a questo frame ($1)'],
  [/^Una singola immagine viene confermata con ([\d—]+) aggiornamenti del tracker\. Il throughput è una misura di elaborazione, non una frequenza di acquisizione live\.$/,'One still image is confirmed with $1 tracker updates. Throughput measures processing, not live capture frequency.','Una singola immagine viene confermata con $1 aggiornamenti del tracker. Il throughput è una misura di elaborazione, non una frequenza di acquisizione live.'],
  [/^(\d+) frame saltati per campionamento\.$/,'$1 video images skipped by sampling.','$1 frame saltati per campionamento.'],
 ];
 if(language==='en')for(const [pattern,en] of dynamic)if(pattern.test(raw)){translated=raw.replace(pattern,en);break}
 if(language==='it'){
  translated=translated.replace(/^(\d+) decks · (\d+) observed cards$/,'$1 mazzi · $2 carte osservate')
   .replace(/^([\d.]+) physical decks remaining$/,'$1 mazzi fisici rimasti')
   .replace(/^Round (\d+) · wager units$/,'Round $1 · unità di puntata')
   .replace(/^Profit ([\d.+-]+)$/,'Profitto $1').replace(/^Wager ([\d.+-]+)$/,'Puntata $1');
 }
 if(language==='it'&&/^\d+ cards await stable visual evidence$/.test(raw))translated=raw.replace(' cards await stable visual evidence',' carte attendono evidenza video stabile');
 // Preserve separators around dynamic React text fragments.
 if(raw!==text)translated=text.slice(0,text.indexOf(raw))+translated+text.slice(text.indexOf(raw)+raw.length);
 return translated;
}
