export type Language='en'|'it';
/** English is the product default, independently of the browser locale. */
let language:Language='en';
try{if(localStorage.getItem('bjlab.language')==='it')language='it'}catch{}
export const getLanguage=()=>language;
export function setLanguage(value:Language){language=value;try{localStorage.setItem('bjlab.language',value)}catch{};if(typeof document!=='undefined')document.documentElement.lang=value;if(typeof window!=='undefined')window.dispatchEvent(new Event('bjlab:language'))}
const messages:Record<string,string>={
 'Tavolo & decisioni':'Table & decisions','Sistemi di conteggio':'Counting systems','Replay & eventi':'Replay & events','Esperimenti':'Experiments','Regolamento':'Rules','Roadmap completa':'Full roadmap',
 'Ogni carta, una prova.':'Every card, a piece of evidence.','Esplora il gioco. Confronta le decisioni. Ricostruisci il perché.':'Explore the game. Compare decisions. Understand the reasoning.',
 'La stessa shoe, più sistemi.':'One shoe, multiple systems.','Confronta conteggi e tag sugli stessi eventi osservati.':'Compare counts and tags on the same observed events.',
 'Dai pixel allo stato.':'From pixels to state.','Riconoscimento e tracking sul nostro simulatore controllato.':'Recognition and tracking on our controlled simulator.',
 'Il gioco, ricostruibile.':'A game you can reconstruct.','Ispeziona ogni evento e torna al punto in cui lo stato è cambiato.':'Inspect each event and return to any state transition.',
 'Le idee incontrano i numeri.':'Ideas meet evidence.','Esperimenti riproducibili con seed, regole e incertezza dichiarati.':'Reproducible experiments with explicit seeds, rules and uncertainty.',
 'Le regole cambiano il gioco.':'Rules change the game.','Configura un regolamento esplicito per il simulatore e il solver.':'Configure explicit rules for the simulator and solver.',
 'Un laboratorio completo.':'A complete laboratory.','Tutti i requisiti integrati, con evidenze e stato di verifica.':'Integrated requirements with evidence and verification status.',
 'Carta':'Hit','Stai':'Stand','Raddoppia':'Double','Dividi':'Split','Resa':'Surrender','Assicurazione':'Insurance','Rifiuta assicurazione':'Decline insurance','Continua':'Continue','Distribuisci':'Deal','Carta coperta':'Face-down card','Coperta':'Face down',
 'IL LABORATORIO':'THE LABORATORY','LABORATORIO':'LABORATORY','Ambiente di ricerca':'Research environment','Simulatore controllato':'Controlled simulator','Backend connesso':'Backend connected','Connessione…':'Connecting…','Backend non raggiungibile':'Backend unavailable','OSSERVA · CALCOLA · VERIFICA':'OBSERVE · CALCULATE · VERIFY','Nuova sessione':'New session',
 'Aspetto del simulatore':'Simulator appearance','Design carte':'Card design','Classico':'Classic','Essenziale':'Minimal','Velocità distribuzione':'Deal speed','Istantanea':'Instant','Rapida':'Fast','Lenta':'Slow','Gli intervalli cambiano l’animazione delle carte; il seed mantiene lo stesso gioco.':'Timing changes the card animation; the seed preserves the same game.',
 'Backend locale non connesso':'Local backend disconnected','Per usare questa pagina esegui run.ps1 nella cartella dei sorgenti e tienilo aperto. L’app desktop avvia il proprio backend quando la apri.':'Run run.ps1 from the source folder and keep it open. The desktop app starts its backend when opened.','Riconnetti':'Reconnect','Operazione non completata':'Operation not completed',
 'Il backend locale non risponde. Per questa pagina avvia run.ps1 dalla cartella dei sorgenti, oppure apri l’app desktop.':'The local backend is not responding. Start run.ps1 from the source folder, or open the desktop app.','Risposta del backend non valida. Riprova la connessione.':'Invalid backend response. Reconnect and try again.','Analisi non disponibile.':'Analysis unavailable.','Il file deve contenere una lista di eventi.':'The file must contain a list of events.',
 ' mazzi · ':' decks · ',' carte osservate':' observed cards','In attesa':'Waiting','Hi-Lo · eventi esposti':'Hi-Lo · exposed events',' mazzi fisici rimasti':' physical decks remaining','Normalizzato ai mazzi rimasti':'Normalized by remaining decks','RISULTATO SESSIONE':'SESSION RESULT','Round ':'Round ',' · unità di puntata':' · wager units','Nessuna mano giocata':'No hands played',
 'Simulatore':'Simulator','Turno giocatore':'Player turn','Mano conclusa':'Hand complete','Resa anticipata':'Early surrender','Pronto':'Ready','BANCO':'DEALER','MANO':'HAND','Profitto ':'Profit ','Puntata ':'Wager ','Puntata':'Wager','Il tuo prossimo esperimento':'Your next experiment','inizia con una mano.':'starts with a hand.','unità':'units',
 'Decisioni & EV':'Decisions & EV','Budget solver':'Solver budget','Ricalcola':'Recalculate','Calcolo degli EV':'Calculating EV','Regole e carte osservabili della mano corrente.':'Rules and observable cards of the current hand.','SOLUZIONE ESATTA':'EXACT SOLUTION','ANALISI · PRECISIONE DICHIARATA':'ANALYSIS · EXPLICIT PRECISION','Analisi parziale':'Partial analysis','Solver matematico':'Mathematical solver','EV condizionato alle informazioni osservate.':'EV conditional on observed information.','Consultare metodo e note per il livello di precisione.':'See method and notes for the precision level.','Esperimento concluso':'Experiment complete','Una decisione alla volta':'One decision at a time','Gli EV vengono calcolati quando è il turno del giocatore.':'EV is calculated during the player turn.','CONFRONTO STRATEGIE':'STRATEGY COMPARISON','Composizione':'Composition','Non calcolata':'Not calculated',
 'Pool non osservato':'Unobserved pool','Per valore · include carte nascoste':'By value · includes hidden cards','Stato dello shoe':'Shoe state','Fonte dello stato':'State source','Simulatore nativo':'Native simulator','Carte fisiche rimaste':'Physical cards remaining','Carte non esposte':'Unexposed cards','Penetrazione':'Penetration','Verifica attraverso i pixel':'Verify through pixels',
 'Tema':'Theme','Verde':'Green','Blu':'Navy','Bordeaux':'Burgundy','Sovrapposizione':'Overlap','Analizza frame':'Analyze image','Carica immagine':'Upload image','Frame controllato':'Controlled image','Frame del simulatore per riconoscimento carte':'Simulator image for card recognition','Nessuna sessione':'No session','Le etichette del simulatore restano separate dal detector. Il frame contiene soltanto le carte esposte.':'Simulator labels remain separate from the detector. The image contains only exposed cards.','Percezione & tracking':'Perception & tracking','Stato ricostruito e gate':'Reconstructed state and integrity gate','Esporta risultato':'Export result','Osservazioni prima delle decisioni':'Observations before decisions','Avvia l\'analisi per vedere detections, eventi e integrità dello stato.':'Start analysis to inspect detections, events and state integrity.',
 'Sessione JSON':'Session JSON','Eventi CSV':'Events CSV','Importa replay':'Import replay','eventi disponibili':'available events','Posizione replay':'Replay position','EVENTO SELEZIONATO':'SELECTED EVENT','STATO RICOSTRUITO':'RECONSTRUCTED STATE','Nessun evento. Distribuisci una mano per iniziare.':'No events. Deal a hand to get started.','Seleziona un evento per ricostruire lo stato fino a questo punto.':'Select an event to reconstruct the state up to that point.',
 'CONFRONTO POLICIES':'POLICY COMPARISON','Un esperimento ripetibile.':'A reproducible experiment.','Le strategie vengono valutate sulle regole configurate. Metodo e intervalli sono parte del risultato.':'Strategies are evaluated under configured rules. Method and intervals are part of the result.','Composizione (più lenta)':'Composition (slower)','Esegui':'Run','Risultati misurati':'Measured results','Esporta JSON':'Export JSON','Esamina il report completo e i campioni':'Inspect the full report and samples','I risultati appariranno qui.':'Results will appear here.','Nessun numero dimostrativo: ogni risultato arriva da un esperimento eseguito.':'Each result comes from an executed experiment.',
 'Regolamento & riproducibilità':'Rules & reproducibility','SI APPLICA A UNA NUOVA SESSIONE':'APPLIES TO A NEW SESSION','Mazzi':'Decks','Qualsiasi due carte':'Any two cards','Nessun double':'No double','Nessuna':'None','Perdita ENHC':'ENHC loss','Tutte le puntate':'All wagers','Solo puntata iniziale (OBO)':'Original bet only (OBO)','Massimo mani split':'Maximum split hands','Le modifiche non cambiano una mano già distribuita.':'Changes do not alter a hand already dealt.','Applica e crea sessione':'Apply and create session',
 'Tutti i requisiti, una prova alla volta':'Every requirement, backed by evidence','OBIETTIVO COMPLETO':'PROJECT REQUIREMENTS','Motore · Solver · Vision · Tracking · Replay · Benchmark · Riferimenti · Desktop':'Engine · Solver · Vision · Tracking · Replay · Benchmarks · References · Desktop','Verificato':'Verified','Parziale':'Partial','Da verificare':'To verify','Caricamento della matrice dei requisiti…':'Loading requirements matrix…','Matematica riproducibile. Stato osservabile. Prove ispezionabili.':'Reproducible mathematics. Observable state. Inspectable evidence.',
 'Sistemi sulla stessa sequenza osservata':'Systems on the same observed sequence','Esporta':'Export','carte esposte nello shoe corrente. Le carte coperte entrano nel conteggio quando vengono rivelate.':'exposed cards in the current shoe. Hidden cards enter the count when revealed.','Arrotondamento TC':'True-count rounding','Troncamento':'Truncate','Intero più vicino':'Nearest integer','Nessuno':'None','Sistema':'System','TC arrotondato':'Rounded TC','Normalizzazione':'Normalization','Mazzi rimasti':'Remaining decks','Il denominatore usa le carte fisiche rimaste dichiarate dal simulatore. Nella percezione questa quantità deve essere stimata separatamente.':'The denominator uses physical remaining cards declared by the simulator. Perception estimates this quantity separately.','Definisci un sistema personalizzato':'Define a custom counting system','Nome':'Name','Sistema bilanciato':'Balanced system','Valida e calcola':'Validate and calculate','I tag vengono validati rispetto alla composizione di un mazzo. Il risultato usa gli stessi eventi esposti del confronto.':'Tags are validated against deck composition. The result uses the same exposed events as the comparison.','Il mio sistema':'My counting system','Servono dieci tag numerici, da Asso a 10, separati da virgole.':'Enter ten numeric tags from Ace through ten, separated by commas.',
 'Stima del numero di mazzi':'Deck-count estimate','Numero di mazzi':'Number of decks',' · esito del clip':' · clip outcome','KNOWN · DICHIARATO':'KNOWN · DECLARED','INFERRED · INCERTO':'INFERRED · UNCERTAIN',' mazzi':' decks','mazzi':'decks','Numero non determinato':'Number undetermined','Sessione configurata':'Configured session','Dichiarazione per l’immagine':'Declared for the image','Dichiarazione per il video':'Declared for the video','Carte confermate dal tracker':'Cards confirmed by the tracker','Il valore proviene dalla configurazione dichiarata.':'The value comes from declared configuration.','La distribuzione deriva dalle carte confermate; il massimo del posteriore non rende noto il numero di mazzi. Il solver resta bloccato finché manca un inventario affidabile.':'The distribution comes from confirmed cards; the posterior maximum does not establish the deck count. Analysis is gated until inventory is reliable.','Osservazioni:':'Observations:','Evidenza incompatibile con i candidati: revisione necessaria.':'Evidence conflicts with the candidates; review required.','Assunzioni della stima':'Estimation assumptions',
 'Replay dei frame video':'Video image replay','Replay dei frame':'Video replay','Clip di un singolo round · frame campionati':'Single-round clip · sampled video','Frame precedente':'Previous image','Frame successivo':'Next image','Posizione frame video':'Video position','Frame sorgente':'Source image','Frame video ':'Video image ','Bounding box del frame video':'Video detection boxes','Anteprima non inclusa nel report.':'Preview not included in the report.','Stato fino a questo frame':'State up to this image','Eventi fino a questo frame (':'Events up to this image (','Detections del frame':'Image detections',
 'EV misurato & incertezza':'Measured EV & uncertainty','Profitto netto medio per unità di puntata iniziale. Gli intervalli descrivono il campionamento fra batch indipendenti.':'Mean net profit per initial wager unit. Intervals describe sampling across independent batches.','Il budget di tempo è terminato: il report usa soltanto i round effettivamente completati.':'The time budget ended; the report uses completed rounds only.','IC 95%:':'95% CI:','non disponibile':'unavailable','decisioni con fallback':'fallback decisions','DIFFERENZE TRA POLICIES · BATCH ABBINATI':'POLICY DIFFERENCES · PAIRED BATCHES','· IC 95%':'· 95% CI',
 'Non misurato':'Not measured','Non misurati':'Not measured','Bounding box delle carte riconosciute':'Recognized card detection boxes','Metriche della percezione':'Perception metrics','Misure della pipeline':'Pipeline measurements','Video locale':'Local video','Immagine importata':'Uploaded image','Frame del simulatore':'Simulator image','Latenza pixel':'Pixel latency','completa':'complete','media':'mean','OCR metadati':'Metadata OCR','Frame distinti analizzati':'Distinct images analyzed','FPS dello stream':'Stream FPS','Frame persi':'Dropped images','Latenza frame p95':'p95 image latency','Frame decodificati':'Decoded images','Il throughput include decodifica ed elaborazione dei frame campionati.':'Throughput includes decoding and processing of sampled video images.','Una singola immagine viene confermata con ':'One still image is confirmed with ',' aggiornamenti del tracker. Il throughput è una misura di elaborazione, non una frequenza di acquisizione live.':' tracker updates. Throughput measures processing, not live capture frequency.',' frame saltati per campionamento.':' video images skipped by sampling.',
 'Calibrazione, video e stato osservato':'Calibration, video and observed state','Chiudi strumenti':'Close tools','Apri strumenti':'Open tools','EV dalla percezione':'EV from perception','Il gate verifica lo stato ricostruito prima del calcolo.':'The integrity gate checks reconstructed state before analysis.','Questo import è indipendente. Analizza il frame del simulatore o associa esplicitamente un’immagine alla sessione.':'This import is independent. Analyze the simulator image or explicitly attach an image to the session.','ANALISI BLOCCATA DAL GATE':'ANALYSIS GATED','RISULTATO DELLO STATO OSSERVATO':'OBSERVED-STATE RESULT','Esporta analisi':'Export analysis','Mazzi dichiarati per l’import':'Declared decks for import','Sconosciuti':'Unknown','Associa l’immagine al tracker della sessione attiva':'Attach the image to the active session tracker','La configurazione dichiarata non dimostra che lo shoe sia stato osservato dall’inizio. Importa clip di un singolo round.':'Declared configuration does not prove observation from the start of the shoe. Import single-round clips.','Normalizza un’immagine':'Normalize an image','Seleziona gli angoli in ordine: alto sinistra, alto destra, basso destra, basso sinistra. Le zone sono rettangoli [x, y, larghezza, altezza] sul frame 960 × 600.':'Select corners in order: top left, top right, bottom right, bottom left. Zones are [x, y, width, height] rectangles on the 960 × 600 image.','Immagine da calibrare':'Image to calibrate','Immagine: seleziona i quattro angoli del tavolo':'Image: select the four table corners','/ 4 angoli':'/ 4 corners','Azzera':'Reset','Zone di riconoscimento':'Recognition zones','Calibra e importa':'Calibrate and import','Seleziona un’immagine.':'Select an image.','Indica tutti i quattro angoli oppure azzera la selezione.':'Select all four corners or reset the selection.','Lettura del file non riuscita.':'Could not read the file.','Il video supera 64 MiB.':'The video exceeds 64 MiB.','Analizza un video locale':'Analyze a local video','La ricostruzione usa i frame decodificati. Il report distingue le carte stabili dalle osservazioni ambigue.':'Reconstruction uses decoded video. The report distinguishes stable cards from ambiguous observations.','Un frame ogni':'Sample every','Massimo frame':'Maximum images','Carica video':'Upload video','Correggi una carta osservata':'Correct an observed card','Usa l’identità logica riportata nello stato. La correzione viene aggiunta al registro con la tua motivazione.':'Use the logical identity shown in state. The correction and your reason are recorded in the journal.','ID logico':'Logical ID','Valore':'Rank','Seme':'Suit','Motivazione':'Reason','Motivazione della correzione':'Correction reason','Registra correzione':'Record correction',
 'Condivisione dello schermo':'Screen sharing','Osserva una finestra o lo schermo':'Observe a window or the screen','Condividi finestra o schermo':'Share window or screen','Scegli la sorgente…':'Choose a source…','Condivisione attiva':'Sharing active','In attesa della tua scelta':'Waiting for your selection','Nessuna sorgente condivisa':'No source shared','Ferma condivisione':'Stop sharing','Annulla':'Cancel','Anteprima della sorgente condivisa':'Shared-source preview','Acquisisci fotogramma':'Capture image','Attendi che l’anteprima sia pronta.':'Wait for the video preview to be ready.','Acquisizione del fotogramma non disponibile.':'Image capture unavailable.','Acquisizione del fotogramma non riuscita.':'Image capture failed.','Anteprima non avviata. Ferma e riprova la condivisione.':'Preview could not start. Stop and retry sharing.','Condivisione annullata o non autorizzata. Puoi riprovare e scegliere la finestra.':'Sharing cancelled or denied. Retry and select a window.','La sorgente non è acquisibile. Scegli un’altra finestra o carica uno screenshot.':'Cannot capture this source. Choose another window or upload an image.','Impossibile avviare la condivisione.':'Could not start sharing.','Questo browser non supporta la condivisione. Apri questa pagina in Chrome o Edge, oppure carica uno screenshot.':'This browser does not support sharing. Open this page in Chrome or Edge.',
 'Scegli tu la sorgente nel selettore del browser. L’anteprima resta locale. Acquisisci un fotogramma, seleziona il tavolo nell’immagine e premi «Calibra e importa» per analizzarlo.':'Choose the source in the browser picker. For continuous observation, use Live vision. This legacy tool imports individual images.',
 'Fotogramma pronto nella sezione «Normalizza un’immagine» qui sotto. La cattura non garantisce il riconoscimento di carte con grafica diversa da quella del laboratorio.':'Image ready under Normalize an image. Other card artwork requires separate validation.',
 'Usa Chrome o Edge su localhost. Nei browser integrati la condivisione può non essere disponibile; resta possibile caricare uno screenshot. Chiudendo gli strumenti o cambiando sezione la condivisione si ferma.':'Use Chrome or Edge on localhost. Integrated browsers may not support display capture. Closing these legacy tools stops their source.',
 'Language':'Lingua','Live vision':'Visione live','Watch the game. Follow every decision.':'Osserva la partita. Segui ogni decisione.','Continuous video, persistent card tracking and probability estimates.':'Video continuo, tracking persistente e stime delle probabilità.',
 'Share screen':'Condividi schermo','Stop video':'Ferma video','Run lab demo':'Avvia demo del laboratorio','Open simulator window':'Apri finestra simulatore','Floating advisor':'Consigliere flottante','Waiting for video':'In attesa del video','Video connected':'Video connesso','Start observing':'Avvia osservazione','Stop observing':'Ferma osservazione','Apply calibration':'Applica calibrazione','Clear corners':'Azzera angoli','Table calibration':'Calibrazione del tavolo','Selected corners':'Angoli selezionati','Observe from a new shoe':'Osserva da un nuovo shoe','Player turn (manual layout)':'Turno del giocatore (layout manuale)','Samples per action':'Campioni per azione','Video processing':'Elaborazione video','Observed cards':'Carte osservate','Running count':'Running count','True count':'True count','Win':'Vittoria','Push':'Parità','Loss':'Sconfitta','Estimated EV':'EV stimato','Recommended action':'Azione consigliata','Waiting for stable cards':'In attesa di carte stabili','Decision stale — waiting for fresh video':'Consiglio scaduto — attendo nuovo video','No source selected':'Nessuna sorgente selezionata','Lab video demo':'Demo video del laboratorio','Screen video':'Video dello schermo','Pause bot':'Ferma bot','Resume bot':'Riprendi bot','New shoe':'Nuovo shoe','Export observed events':'Esporta eventi osservati','Cards':'Carte','Dealer':'Banco','Player':'Giocatore','Probability estimates':'Stime delle probabilità','95% confidence interval':'Intervallo di confidenza al 95%','Simulated outcomes':'Esiti simulati','No positive EV detected':'Nessun EV positivo rilevato','Positive estimated EV':'EV stimato positivo','Waiting for a decision':'In attesa di una decisione','Fresh shoe declared':'Nuovo shoe dichiarato','Partial observed count':'Conteggio parziale osservato','No clear ranking':'Ordine delle azioni incerto','Close advisor':'Chiudi consigliere','Open in default browser':'Apri nel browser predefinito',
};
const liveItalian:Record<string,string>={
 'Opening advisor…':'Apertura del consigliere…','Floating live advisor':'Consigliere live flottante','Pop out advisor':'Apri consigliere in finestra',
 'Advisor is shown in this page. Use Chrome or Edge for a separate always-on-top window.':'Il consigliere è mostrato in questa pagina. Usa Chrome o Edge per una finestra separata sempre in primo piano.',
 'CONTINUOUS SCREEN VIDEO':'VIDEO CONTINUO DELLO SCHERMO','Share once. Follow the whole game.':'Condividi una volta. Segui tutta la partita.',
 'Choose a screen, window or browser tab. Observation continues automatically; no image capture button is needed.':'Scegli schermo, finestra o scheda del browser. L’osservazione prosegue automaticamente, senza acquisizioni manuali.',
 'Continuous shared video':'Video condiviso continuo','Live recognized cards':'Carte riconosciute in diretta','Give the lab a live video source.':'Fornisci al laboratorio una sorgente video live.',
 'Share your simulation, or run the lab demo to test video → recognition → tracking → advice.':'Condividi la tua simulazione oppure avvia la demo per provare video → riconoscimento → tracking → consiglio.',
 'Video paused':'Video in pausa','Selected corners:':'Angoli selezionati:','500 · fast':'500 · rapido','1,500 · balanced':'1.500 · bilanciato','5,000 · precise':'5.000 · preciso',
 'For a full screen, select the table corners: top left, top right, bottom right, bottom left. Keep its position fixed while observing.':'Per lo schermo completo seleziona gli angoli del tavolo: alto sinistra, alto destra, basso destra, basso sinistra. Mantieni la posizione fissa durante l’osservazione.',
 'Distinct observations':'Osservazioni distinte','Skipped while busy':'Saltate durante l’elaborazione',
 'Processing runs locally. The preview is video; the analysis samples it automatically with one upload in flight. Guidance expires when the video stops updating.':'L’elaborazione è locale. L’anteprima è video; l’analisi lo campiona automaticamente, con un solo invio alla volta. Il consiglio scade quando il video smette di aggiornarsi.',
 'Recognition scope and probability method':'Ambito del riconoscimento e metodo probabilistico',
 'The included detector is validated for lab card artwork. Other artwork needs a trained detector and a separate test. Counts cover only what the video has actually observed. Select a new shoe before relying on a full-shoe count.':'Il detector incluso è validato sulla grafica delle carte del laboratorio. Altre grafiche richiedono un detector addestrato e una verifica separata. Il conteggio copre ciò che il video ha osservato. Parti da un nuovo shoe per un conteggio completo.',
 'Win, push and loss describe net profit of the active hand, including any new splits. Existing other hands are excluded. EV estimates use finite-pool Monte Carlo with generated basic continuation; sampling intervals do not measure perception error.':'Vittoria, parità e sconfitta descrivono il profitto netto della mano attiva, inclusi nuovi split. Le altre mani già presenti sono escluse. Gli EV usano Monte Carlo su pool finito con continuazione basic generata; gli intervalli di campionamento non misurano l’errore percettivo.',
 'Display sharing needs Chrome or Edge on localhost.':'La condivisione richiede Chrome o Edge su localhost.','Observe → verify → decide':'Osserva → verifica → decidi','95% confidence interval:':'Intervallo di confidenza al 95%:',
 'simulated outcomes per action ·':'esiti simulati per azione ·','Monte Carlo estimate':'Stima Monte Carlo','Exact':'Esatto','Action':'Azione','Dealer blackjack:':'Blackjack del banco:','· Insurance EV:':'· EV assicurazione:',
 'Advice is hidden until new video arrives.':'Il consiglio resta nascosto fino a un nuovo video.','Select a video source to begin.':'Seleziona una sorgente video per iniziare.',
 'Need at least two player cards and exactly one visible dealer upcard.':'Servono almeno due carte del giocatore e una sola carta scoperta del banco.',
 'Waiting for a player decision in the video.':'In attesa di una decisione del giocatore nel video.',
 'Visible round context is changing; waiting for stable video evidence.':'Il contesto della mano sta cambiando; attendo evidenza video stabile.',
 'Some card-shaped regions could not be read.':'Alcune regioni con forma di carta non sono leggibili.','Active player cards are not fully visible.':'Le carte della mano attiva non sono tutte visibili.',
 'No readable legal player controls; calibrate the table or declare a manual player turn.':'Comandi del giocatore non leggibili: calibra il tavolo oppure dichiara il turno manuale.',
 'Select all four table corners before observing.':'Seleziona tutti i quattro angoli prima dell’osservazione.','Video processing failed.':'Elaborazione video non riuscita.',
 'Video processing timed out. Waiting for a fresh observation.':'Tempo di elaborazione scaduto. Attendo una nuova osservazione.','Video preview could not start. Stop and retry.':'Anteprima video non avviata. Ferma e riprova.',
 'The advisor popup was blocked. Allow popups for this local page.':'Il pop-up è stato bloccato. Consenti i pop-up per questa pagina locale.',
 'Opened the local app in your browser. Keep the desktop app open while sharing.':'Applicazione locale aperta nel browser. Tieni aperta l’app desktop durante la condivisione.',
 'Export observation':'Esporta osservazione','BLACKJACK VISION LAB / VIDEO SOURCE':'BLACKJACK VISION LAB / SORGENTE VIDEO','A table your live advisor can watch.':'Un tavolo che il consigliere live può osservare.',
 'Share this window from Live vision, select the four table corners, and play manually or start the bot. The advisor reads the visible video, including round labels and buttons.':'Condividi questa finestra da Visione live, seleziona i quattro angoli e gioca manualmente oppure avvia il bot. Il consigliere legge il video visibile, comprese etichette e pulsanti.',
 'Visible blackjack simulation table':'Tavolo visibile della simulazione blackjack','Starting simulator…':'Avvio del simulatore…','New session':'Nuova sessione','· Net profit':'· Profitto netto','units':'unità','player':'giocatore','settled':'conclusa','ready':'pronto','insurance':'assicurazione','early_surrender':'resa anticipata',
};
// Legacy labels use Italian keys. New features use English keys; both translate.
const primary=new Map<string,string>(),secondary=new Map<string,string>();
let englishKeys=false;
for(const [key,value] of Object.entries(messages)){
 if(key==='Language')englishKeys=true;
 const it=(englishKeys?value:key).trim(),en=(englishKeys?key:value).trim();
 primary.set(it,en);if(!secondary.has(en))secondary.set(en,it);
}
for(const [en,it] of Object.entries(liveItalian)){primary.set(it,en);secondary.set(en,it)}
export function t(text:string):string{
 const raw=text.trim();
 let translated=language==='en'?(primary.get(raw)||raw):(secondary.get(raw)||raw);
 const dynamic: [RegExp,string,string][]=[
  [/^(\d+) mazzi · (\d+) carte osservate$/,'$1 decks · $2 observed cards','$1 mazzi · $2 carte osservate'],
  [/^([\d.]+) mazzi fisici rimasti$/,'$1 physical decks remaining','$1 mazzi fisici rimasti'],
  [/^Round (\d+) · unità di puntata$/,'Round $1 · wager units','Round $1 · unità di puntata'],
  [/^Profitto ([\d.+-]+)$/,'Profit $1','Profitto $1'],
  [/^Puntata ([\d.+-]+)$/,'Wager $1','Puntata $1'],
  [/^(\d+) mazzi$/,'$1 decks','$1 mazzi'],
  [/^Frame video (\d+)$/,'Video image $1','Frame video $1'],
  [/^Eventi fino a questo frame \((\d+)\)$/,'Events up to this image ($1)','Eventi fino a questo frame ($1)'],
  [/^Una singola immagine viene confermata con ([\d—]+) aggiornamenti del tracker\. Il throughput è una misura di elaborazione, non una frequenza di acquisizione live\.$/,'One still image is confirmed with $1 tracker updates. Throughput measures processing, not live capture frequency.','Una singola immagine viene confermata con $1 aggiornamenti del tracker. Il throughput è una misura di elaborazione, non una frequenza di acquisizione live.'],
  [/^(\d+) frame saltati per campionamento\.$/,'$1 video images skipped by sampling.','$1 frame saltati per campionamento.'],
 ];
 if(language==='en')for(const [pattern,en] of dynamic)if(pattern.test(raw)){translated=raw.replace(pattern,en);break}
 if(language==='it'){
  translated=translated.replace(/^(\d+) decks · (\d+) observed cards$/,'$1 mazzi · $2 carte osservate')
   .replace(/^([\d.]+) physical decks remaining$/,'$1 mazzi fisici rimasti')
   .replace(/^Round (\d+) · wager units$/,'Round $1 · unità di puntata')
   .replace(/^Profit ([\d.+-]+)$/,'Profitto $1').replace(/^Wager ([\d.+-]+)$/,'Puntata $1');
 }
 if(language==='it'&&/^\d+ cards await stable visual evidence$/.test(raw))translated=raw.replace(' cards await stable visual evidence',' carte attendono evidenza video stabile');
 // Preserve separators around dynamic React text fragments.
 if(raw!==text)translated=text.slice(0,text.indexOf(raw))+translated+text.slice(text.indexOf(raw)+raw.length);
 return translated;
}
