import {useEffect,useRef,useState} from 'react';
import {api,Rules} from './api';
import {LiveAdvisor} from './LiveVision';
import {localize} from './localize';
import {parseCardInput} from './card-input';

export default function ImageAdvisor({rules,connected,file}:{rules:Rules;connected:boolean;file?:File|null}){
 const [image,setImage]=useState(''),[report,setReport]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[player,setPlayer]=useState(''),[dealer,setDealer]=useState('');
 const [fromSplit,setFromSplit]=useState(false),[splitHands,setSplitHands]=useState(2),[observed,setObserved]=useState('');
 const [clef,setClef]=useState<any>(null),[clefBusy,setClefBusy]=useState(false);
 const upload=useRef<HTMLInputElement>(null),generation=useRef(0),alive=useRef(true),work=useRef<((file:File)=>Promise<void>)|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++}},[]);
 useEffect(()=>{if(file)void work.current?.(file)},[file]);
 const inspect=async(file:File)=>{const attempt=++generation.current;setBusy(true);setError('');setReport(null);try{
  if(!file.type.startsWith('image/')||file.type==='image/svg+xml')throw new Error('Choose a PNG, JPEG or WebP image.');
  if(file.size>8*1024*1024)throw new Error('Image exceeds 8 MiB. Crop the table or use a smaller image.');
  const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');const scale=Math.min(1,1920/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const url=canvas.toDataURL('image/png');
  if(attempt!==generation.current||!alive.current)return;setImage(url);setClef(null);
  const value=await api('/advisor/image',{rules,image_base64:url.split(',')[1],player_turn:true});if(attempt!==generation.current||!alive.current)return;setReport(value);setPlayer(value.player.join(' '));setDealer(value.dealer[0]||'');
 }catch(e){if(attempt===generation.current&&alive.current)setError(e instanceof Error?e.message:String(e))}finally{if(attempt===generation.current&&alive.current)setBusy(false)}};
 work.current=inspect;
 const confirm=async()=>{const attempt=++generation.current;setBusy(true);setError('');setReport(null);try{const body={rules,from_split:fromSplit,split_hands:fromSplit?splitHands:1,observed:parseCardInput(observed,'Observed cards'),player:parseCardInput(player,'Player cards',2,24),dealer:parseCardInput(dealer,'Dealer upcard',1,1)[0]};const quick=await api('/advisor/manual',{...body,estimate:false});if(attempt!==generation.current||!alive.current)return;setReport(quick);const value=await api('/advisor/manual',body);if(attempt===generation.current&&alive.current)setReport(value)}catch(e){if(attempt===generation.current&&alive.current)setError(e instanceof Error?e.message:String(e))}finally{if(attempt===generation.current&&alive.current)setBusy(false)}};
 const inspectClef=async()=>{const attempt=generation.current;setClefBusy(true);try{const value=await api('/models/clef/classify',{image_base64:image.split(',')[1]});if(alive.current&&attempt===generation.current)setClef(value)}catch(e){if(alive.current&&attempt===generation.current)setClef({error:e instanceof Error?e.message:String(e)})}finally{if(alive.current)setClefBusy(false)}};
 return localize(<section className="image-advisor"><div className="panel image-drop-zone" tabIndex={0} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('dragging')}} onDragLeave={e=>e.currentTarget.classList.remove('dragging')} onDrop={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.classList.remove('dragging');const file=e.dataTransfer.files[0];if(file)void inspect(file)}}><div className="section-label">ONE IMAGE · ONE DECISION</div><h2>Paste. Drop. Understand the hand.</h2><p>Ctrl + V pastes an image anywhere in this view. A still image gives current-hand advice; it cannot reconstruct earlier cards.</p><input ref={upload} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{if(e.target.files?.[0])void inspect(e.target.files[0]);e.target.value=''}}/><button className="button primary" disabled={!connected||busy} onClick={()=>upload.current?.click()}>{busy?'Reading image…':'Choose an image'}</button>{image&&<img src={image} alt="Pasted or dropped blackjack table"/>}
 <details open={!report?.advice}><summary>Confirm or enter cards</summary><p>For unsupported artwork, enter the visible player cards and dealer upcard. Confirm that it is your turn. A, 2–10, J, Q and K are accepted.</p><div className="manual-card-input"><label>Player cards<input value={player} onChange={e=>{setPlayer(e.target.value);setReport(null);setBusy(false);generation.current++}} placeholder="A 7"/></label><label>Dealer upcard<input value={dealer} onChange={e=>{setDealer(e.target.value);setReport(null);setBusy(false);generation.current++}} placeholder="9"/></label><button className="button secondary" disabled={!connected||busy} onClick={()=>void confirm()}>Confirm player turn & analyze</button><div className="manual-advanced"><label className="toggle-label"><input type="checkbox" checked={fromSplit} onChange={e=>{setFromSplit(e.target.checked);setReport(null);setBusy(false);generation.current++}}/>Hand created by a split</label>{fromSplit&&<label>Hands in this round<input type="number" min="2" max="8" value={splitHands} onChange={e=>{setSplitHands(Number(e.target.value));setReport(null);setBusy(false);generation.current++}}/></label>}<label>Observed cards (optional, includes current cards)<input value={observed} onChange={e=>{setObserved(e.target.value);setReport(null);setBusy(false);generation.current++}} placeholder="10 10 6 2 5"/></label></div></div></details><details className="optional-model"><summary>Optional Clef scene check</summary><p>Experimental image classification only. Confidence is not an outcome probability. Start the separate local Clef runtime first.</p><button className="button secondary" disabled={!image||clefBusy} onClick={()=>void inspectClef()}>{clefBusy?'Classifying…':'Classify this image with Clef'}</button>{clef&&<pre>{JSON.stringify(clef,null,2)}</pre>}</details>{error&&<p className="tool-error" role="alert">{error}</p>}</div><LiveAdvisor report={report} stale={false}/></section>);
}
