import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import SimulatorWindow from './SimulatorWindow';
import NativeAdvisor from './NativeAdvisor';
import IntegrationLab, {IntegrationAdvisor} from './IntegrationLab';
import './style.css';
import './dark.css';
const query = new URLSearchParams(location.search);
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{query.has('r1-advisor')?<IntegrationAdvisor/>:query.has('integration')?<IntegrationLab/>:query.has('advisor')?<NativeAdvisor/>:query.has('simulator')?<SimulatorWindow/>:<App/>}</React.StrictMode>);
