import {useEffect,useRef,useState} from 'react';
import {Rules} from './api';
import LiveVision from './LiveVision';
import {Setup} from './Setup';
import {localize} from './localize';
import {SharedDisplay} from './preferences';
type Table={id:string;name:string;rules:Rules;game:'blackjack'|'monitor';revision:number};
export default function MultiTable({rules,connected}:{rules:Rules;connected:boolean}){
 const [tables,setTables]=useState<Table[]>([{id:crypto.randomUUID(),name:'Table 1',rules:{...rules},game:'blackjack',revision:0}]),[editing,setEditing]=useState<string|null>(null),[confirm,setConfirm]=useState(false),[dontAsk,setDontAsk]=useState(false),[epoch,setEpoch]=useState(0);
 const capture=useRef(new SharedDisplay()),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>()=>capture.current.stop(),[]);
 useEffect(()=>{if(confirm)dialog.current?.showModal()},[confirm]);
 useEffect(()=>{setTables(previous=>previous.map((table,i)=>i===0?{...table,rules:{...rules},revision:table.revision+1}:table))},[JSON.stringify(rules)]);
 const add=()=>{if(tables.length>=5)return;setTables(previous=>[...previous,{id:crypto.randomUUID(),name:'Table '+(previous.length+1),rules:{...rules},game:'blackjack',revision:0}]);setConfirm(false);if(dontAsk)localStorage.setItem('bjlab.reuseRules','yes')};
 return localize(<div className={'multi-table tables-'+tables.length}><div className="table-manager"><div><div className="section-label">LIVE WORKSPACE</div><h2>{tables.length===1?'One table. One clear decision.':tables.length+' independent tables'}</h2><p>Each table has its own card history, rules and advisor. A shared display is selected once; calibrate a separate table region for each observer.</p></div><div><button className="button secondary" disabled={tables.length>=5} onClick={()=>localStorage.getItem('bjlab.reuseRules')==='yes'?add():setConfirm(true)}>+ Add table</button><button className="text-button" onClick={()=>{capture.current.stop();setEpoch(v=>v+1)}}>Stop all sources</button></div></div>
 {tables.map((table,index)=><section className="table-workspace" key={table.id}><header className="table-workspace-header"><span className="table-number">{String(index+1).padStart(2,'0')}</span><input aria-label="Table name" value={table.name} onChange={e=>setTables(previous=>previous.map(t=>t.id===table.id?{...t,name:e.target.value}:t))}/><span className="badge">{table.rules.decks} decks · {table.rules.hit_soft17?'H17':'S17'}</span><select aria-label="Game type" value={table.game} onChange={e=>setTables(previous=>previous.map(t=>t.id===table.id?{...t,game:e.target.value as Table['game'],revision:t.revision+1}:t))}><option value="blackjack">Blackjack</option><option value="monitor">Poker / other · monitor only</option></select><button className="text-button" onClick={()=>setEditing(table.id)}>Configure</button>{tables.length>1&&<button className="text-button" aria-label={'Remove '+table.name} onClick={()=>setTables(previous=>previous.filter(t=>t.id!==table.id))}>Remove</button>}</header>
 <LiveVision key={table.id+'-'+table.revision+'-'+epoch} rules={table.rules} connected={connected} tableName={table.name} demoSeed={42+index*97} defaultSamples={tables.length>1?500:1500} acquireSource={()=>capture.current.acquire()} releaseSource={stream=>capture.current.release(stream)} interval={tables.length>1?Math.max(500,tables.length*100):350} monitorOnly={table.game==='monitor'}/></section>)}
 {editing&&<Setup rules={tables.find(t=>t.id===editing)!.rules} onClose={()=>setEditing(null)} onSave={value=>{setTables(previous=>previous.map(t=>t.id===editing?{...t,rules:value,revision:t.revision+1}:t));setEditing(null)}}/>}
 {confirm&&<dialog ref={dialog} className="setup-dialog reuse-dialog" aria-labelledby="reuse-title" onCancel={()=>setConfirm(false)}><div className="section-label">NEW TABLE</div><h2 id="reuse-title">Use your saved configuration?</h2><p>{rules.decks} decks · dealer {rules.hit_soft17?'hits':'stands'} on soft 17 · blackjack payout {rules.blackjack_payout===1.5?'3 : 2':'6 : 5'}.</p><p>The new table starts with an empty observed history. Its count stays independent from the other tables.</p><label className="toggle-label"><input type="checkbox" checked={dontAsk} onChange={e=>setDontAsk(e.target.checked)}/>Use these settings without asking again</label><div className="dialog-actions"><button className="button secondary" onClick={()=>setConfirm(false)}>Cancel</button><button className="button primary" onClick={add}>Add independent table</button></div></dialog>}
 </div>);
}
