import {useEffect,useRef,useState} from 'react';
import {Rules} from './api';
import {GameMode,rulesForMode} from './preferences';
import {localize} from './localize';

export function Setup({rules,onSave,onClose}:{rules:Rules;onSave:(rules:Rules)=>void;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[draft,setDraft]=useState({...rules}),[mode,setMode]=useState<GameMode>(()=>rules.double_rule==='none'&&rules.max_split_hands===1&&rules.surrender==='none'?'simple':JSON.stringify(rules)===JSON.stringify(rulesForMode('standard',rules))?'standard':'custom');
 const [askAgain,setAskAgain]=useState(()=>localStorage.getItem('bjlab.reuseRules')!=='yes');
 const valid=Number.isInteger(draft.max_split_hands)&&draft.max_split_hands>=1&&draft.max_split_hands<=8;
 useEffect(()=>{ref.current?.showModal()},[]);
 return localize(<dialog ref={ref} className="setup-dialog" onCancel={onClose} aria-labelledby="setup-title"><div className="section-label">TABLE CONFIGURATION</div><h2 id="setup-title">A few rules. A useful starting point.</h2><p>Match the actual table. These settings determine legal actions and the strategy reference.</p><p className="help-note">Saving starts a new observer history for this table. Declare a fresh shoe only when the decks have actually been reset.</p><div className="setup-grid">
  <label>Game mode<select value={mode} onChange={e=>{const value=e.target.value as GameMode;setMode(value);setDraft(rulesForMode(value,draft))}}><option value="standard">Standard blackjack</option><option value="simple">Hit / stand only</option><option value="custom">Custom rules</option></select></label>
  <label>Decks<select value={draft.decks} onChange={e=>setDraft({...draft,decks:Number(e.target.value)})}>{[1,2,4,6,8].map(n=><option key={n} value={n}>{n}</option>)}</select></label>
  <label>Dealer on soft 17<select value={draft.hit_soft17?'hit':'stand'} onChange={e=>setDraft({...draft,hit_soft17:e.target.value==='hit'})}><option value="stand">Stand (S17)</option><option value="hit">Hit (H17)</option></select></label>
  <label>Dealer card procedure<select value={draft.enhc?'european':'peek'} onChange={e=>setDraft({...draft,enhc:e.target.value==='european',dealer_peek:e.target.value!=='european'})}><option value="peek">American peek</option><option value="european">European no-hole-card</option></select></label>
  <label>Blackjack payout<select value={draft.blackjack_payout} onChange={e=>setDraft({...draft,blackjack_payout:Number(e.target.value)})}><option value="1.5">3 : 2</option><option value="1.2">6 : 5</option></select></label>
  <label>Surrender<select disabled={mode==='simple'} value={draft.surrender} onChange={e=>setDraft({...draft,surrender:e.target.value})}><option value="none">None</option><option value="late">Late surrender</option><option value="early">Early surrender</option></select></label>
 </div><details><summary>Advanced rules</summary><fieldset disabled={mode==='simple'} className="setup-grid"><label>Double rule<select value={draft.double_rule} onChange={e=>setDraft({...draft,double_rule:e.target.value})}><option value="any">Any two cards</option><option value="9-11">9–11 only</option><option value="10-11">10–11 only</option><option value="none">Disabled</option></select></label><label>Maximum split hands<input type="number" min="1" max="8" value={draft.max_split_hands} onChange={e=>setDraft({...draft,max_split_hands:Number(e.target.value)})}/></label>{(['double_after_split','resplit','resplit_aces','hit_split_aces'] as const).map(key=><label key={key} className="toggle-label"><input type="checkbox" checked={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>{({double_after_split:'Double after split',resplit:'Resplit pairs',resplit_aces:'Resplit aces',hit_split_aces:'Hit split aces'})[key]}</label>)}<label>European dealer blackjack loss<select value={draft.enhc_loss} onChange={e=>setDraft({...draft,enhc_loss:e.target.value})}><option value="all">All wagers</option><option value="original">Original wager only (OBO)</option></select></label></fieldset></details>
 <label className="toggle-label"><input type="checkbox" checked={askAgain} onChange={e=>setAskAgain(e.target.checked)}/>Ask before reusing saved settings</label><p className="help-note">A “shoe” is the collection of cards dealt from the selected decks. Start observing before the first deal for a complete count.</p><div className="dialog-actions"><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={!valid} onClick={()=>{if(askAgain)localStorage.removeItem('bjlab.reuseRules');else localStorage.setItem('bjlab.reuseRules','yes');onSave(draft)}}>Save configuration</button></div></dialog>);
}

const steps=[['Configure your table','Select decks, dealer rules and permitted actions. Each table can have a different configuration.'],['Connect a source','Run the lab demo, share your screen in Chrome or Edge, or paste/drop an image. For a shared screen, select the four corners of each table.'],['Read the short answer','The action is shown first. Aces display their active value and alternative total. Counts update from confirmed exposed cards.'],['Open the details when useful','Expand the advisor for basic strategy, EV, uncertainty and observed composition. The offline strategy library covers hard totals, soft totals, pairs and 550 starting combinations.']];
export function Guide({onClose}:{onClose:()=>void}){const [step,setStep]=useState(0),ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);return localize(<dialog ref={ref} className="setup-dialog guide-dialog" aria-labelledby="guide-title" onCancel={onClose}><div className="section-label">QUICK GUIDE · {step+1} / {steps.length}</div><div className="guide-progress">{steps.map((_,i)=><i key={i} className={i<=step?'active':''}/>)}</div><h2 id="guide-title">{steps[step][0]}</h2><p>{steps[step][1]}</p><div className="guide-illustration">{step===0?<><span>6 decks</span><span>S17</span><span>3 : 2</span></>:step===1?<><span>Video</span><span>Paste</span><span>Drop</span></>:step===2?<><strong>STAND</strong><span>20 · hard total</span></>:<><span>Basic policy</span><span>Count</span><span>EV</span></>}</div><p className="help-note">Analysis and education only. Not financial advice. No system guarantees a winning outcome.</p><div className="dialog-actions"><button className="button secondary" onClick={onClose}>Skip guide</button><button className="button primary" onClick={()=>step===steps.length-1?onClose():setStep(step+1)}>{step===steps.length-1?'Start exploring':'Next'}</button></div></dialog>)}

export function ReuseConfiguration({rules,onClose,onConfirm}:{rules:Rules;onClose:()=>void;onConfirm:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[remember,setRemember]=useState(false);
 useEffect(()=>{ref.current?.showModal()},[]);
 return localize(<dialog ref={ref} className="setup-dialog" aria-labelledby="session-reuse-title" onCancel={onClose}><div className="section-label">NEW SESSION</div><h2 id="session-reuse-title">Use your saved configuration?</h2><p>{rules.decks} decks · {rules.hit_soft17?'H17':'S17'} · {rules.double_rule==='none'?'Hit / stand only':'Custom rules'}.</p><p>The new session starts with a fresh simulated shoe. Match its rules before observing it.</p><label className="toggle-label"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Use these settings without asking again</label><div className="dialog-actions"><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" onClick={()=>{if(remember)localStorage.setItem('bjlab.reuseRules','yes');onConfirm()}}>Start new session</button></div></dialog>);
}
