import {useEffect,useRef,useState} from 'react';
import {api,download,Rules} from './api';
import {localize} from './localize';
const labels:Record<string,string>={hit:'H',stand:'S',double:'D',split:'P',surrender:'R',continue:'C'};
const columns=['A','2','3','4','5','6','7','8','9','10'];
export default function StrategyLibrary({rules}:{rules:Rules}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[group,setGroup]=useState('hard'),[query,setQuery]=useState('');const generation=useRef(0);
 useEffect(()=>{const attempt=++generation.current;setData(null);setError('');void api('/advisor/strategy',{rules}).then(value=>{if(attempt===generation.current)setData(value)}).catch(e=>{if(attempt===generation.current)setError(e.message)});return()=>{generation.current++}},[JSON.stringify(rules)]);
 const rows=data?.table?.[group]||{};
 return localize(<section className="panel strategy-library"><div className="panel-header"><h2>Basic strategy · offline library</h2><span className="badge">{rules.decks} decks · {rules.hit_soft17?'H17':'S17'}</span></div><div className="strategy-intro"><p>A complete rule-generated reference for hard totals, soft totals, pairs and every starting rank combination. Aces may count as 1 or 11. The best usable value is selected automatically.</p><div className="strategy-legend">{Object.entries(labels).map(([name,label])=><span key={name} className={'action-'+name}><b>{label}</b> {name}</span>)}</div><p className="help-note">Independent-draw reference; finite deck composition and count deviations are compared separately. Single-deck composition can differ. These calculations run locally and need no online chart lookup.</p></div>
 {error&&<p className="tool-error" role="alert">{error}</p>}{!data&&!error&&<p className="loading-note">Building the local strategy library…</p>}
 {data&&<><div className="strategy-tabs" role="tablist" aria-label="Strategy groups">{['hard','soft','pairs','natural','combinations'].map(key=><button key={key} role="tab" aria-selected={key===group} className={key===group?'selected':''} onClick={()=>setGroup(key)}>{key==='combinations'?'550 combinations':key==='natural'?'Blackjack':key==='hard'?'Hard totals':key==='soft'?'Soft totals':'Pairs'}</button>)}</div>
 {group==='combinations'?<><label className="combination-search">Filter player / dealer<input value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="A 7, 10 10, dealer 6…"/></label><div className="combination-grid">{data.combinations.filter((row:any)=>!query||(row.player.join(' ')+' DEALER '+row.dealer).includes(query)).map((row:any,i:number)=><div key={i}><span>{row.player.join(' + ')} <small>vs {row.dealer}</small></span><b className={'action-'+row.action}>{row.action}</b></div>)}</div></>:<div className="table-scroll"><table className="strategy-matrix"><thead><tr><th>Player / dealer</th>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{Object.entries(rows).map(([name,cells]:[string,any])=><tr key={name}><th>{group==='pairs'?name+' + '+name:name}</th>{columns.map(up=><td className={'action-'+cells[up].action} key={up} title={cells[up].action+' · model EV '+cells[up].actions[cells[up].action]?.toFixed(4)}>{labels[cells[up].action]||cells[up].action}</td>)}</tr>)}</tbody></table></div>}
 <div className="strategy-footer"><span>550 starting combinations · hard / soft / pairs · legal actions only</span><button className="button secondary" onClick={()=>download('blackjack-strategy-library.json',data)}>Export offline reference</button></div></>}
 </section>);
}
