import {useState} from 'react';
import {api} from './api';
import {localize} from './localize';

export default function ToolsPanel(){
 const [status,setStatus]=useState<any>(null),[busy,setBusy]=useState(false);
 const check=async()=>{setBusy(true);try{setStatus(await api('/models/clef/status'))}catch(e){setStatus({status:'offline',message:e instanceof Error?e.message:String(e)})}finally{setBusy(false)}};
 return localize(<section className="tools-panel"><div className="panel"><div className="section-label">ESSENTIAL PROGRAMS</div><h2>A small core. Optional extras.</h2><p>The Windows app includes its local backend. No Python, Node, API key or paid service is needed to play the lab simulator or use the strategy library.</p><p>Chrome or Edge provides continuous display sharing and, where supported, a separate always-on-top advisor. The system screen picker decides what is shared.</p><p>For a source installation: Python 3.12, Node.js 22 and the pinned project dependencies. Rust and Windows build tools are only needed to create the desktop installer.</p></div><div className="panel"><div className="section-label">OPTIONAL · CLEF</div><h2>Independent visual verification</h2><p>Clef runs in a separate NVIDIA CUDA environment. Its roughly 19 GB model download is optional. It can check card ranks, suits, card count and game phase on a captured image. Model scores are not correctness or outcome probabilities.</p><p>The core advisor uses confirmed cards and mathematical models. The experimental live verifier is tied to the captured hand. Disagreement blocks automatic advice; an inconclusive answer remains visible. Clef does not replace the game engine.</p><button className="button secondary" disabled={busy} onClick={()=>void check()}>{busy?'Checking…':'Check local Clef runtime'}</button>{status&&<p role="status">{status.status==='ready'?status.model+' · '+status.device:status.message}</p>}<a className="text-button" href="https://github.com/youtrustshop-dot/blackjack-vision-lab/blob/main/docs/CLEF.md" target="_blank" rel="noopener">Installation & hardware notes</a></div><div className="panel"><div className="section-label">OPTIONAL · BROWSER EXTENSION</div><h2>A quick tab image</h2><p>The Chrome / Edge helper captures the visible tab after your click. It can copy the image for pasting into the lab or analyze it against your local backend. Continuous video and multi-table tracking are provided by Share screen in the main app.</p><a className="button secondary" href="https://github.com/youtrustshop-dot/blackjack-vision-lab/tree/main/extensions/chromium" target="_blank" rel="noopener">Extension source & setup</a></div></section>);
}
