import {useEffect,useState} from 'react';
import {api,download} from './api';
import {localize} from './localize';

export default function VisionMatrix(){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;void api('/vision/experiments').then(value=>{if(active)setData(value)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 return localize(<section className="panel"><div className="section-label">VISION EXPERIMENT FUNNEL</div><h2>Evidence before promotion.</h2><p>Each stage keeps its baseline, alternatives, status and measured failures. Private development screenshots remain local. Repeated previews are the same session; monitor photos are diagnostic.</p>{error&&<p role="alert">{error}</p>}{data&&<><p>Running package: <b>{data.runtime.package_version}</b> · Detector: <b>{data.runtime.detector_version}</b><br/>Content fingerprint: <code>{data.runtime.source_fingerprint.slice(0,16)}</code><br/>{data.runtime.publication}<br/>Frozen reference: desktop {data.baseline.version} · {data.baseline.commit.slice(0,12)}</p><button className="button secondary" onClick={()=>download('vision-experiments.json',data)}>Export experiment matrix</button><div className="table-scroll"><table><thead><tr><th>Stage</th><th>Candidate</th><th>Status</th><th>Finding / next proof</th></tr></thead><tbody>{data.stages.map((stage:any)=><tr key={stage.id}><td>{stage.stage}</td><td>{stage.candidate}</td><td>{stage.status}</td><td>{stage.finding}</td></tr>)}</tbody></table></div>{data.comparison&&<><h3>Executed development comparison</h3><p>{data.comparison.scope}</p><table><thead><tr><th>Profile</th><th>Correct zone / ranks</th><th>Suit reads</th><th>Offline p95</th></tr></thead><tbody>{Object.entries(data.comparison.aggregates).map(([name,result]:[string,any])=><tr key={name}><td>{name}</td><td>{result.correct_zone_ranks} / {result.visible_cards}</td><td>{result.suit_correct_including_misses} / {result.visible_cards}</td><td>{result.offline_ms_p95.toFixed(0)} ms</td></tr>)}</tbody></table><p>No independent generalization, continuous count reconstruction or capture-to-display result is implied. This first comparison does not promote a model.</p></>}</>}</section>);
}
