/** Functional verification of calibration, counting, observed EV and policy reports. */
import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const pw=require(process.argv[2]||process.env.BJLAB_PLAYWRIGHT_MODULE||'playwright');
const videoFixture=process.argv[3]||process.env.BJLAB_VIDEO_FIXTURE;
const root=path.resolve(import.meta.dirname,'../..');
const browser=await pw.chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({viewport:{width:1440,height:1050}});
const page=await context.newPage();
const checks=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
const screenDir=path.join(root,'docs/screenshots');
try{
 await page.goto(process.env.BJLAB_URL||'http://127.0.0.1:8765');
 await page.getByRole('button',{name:'Distribuisci',exact:true}).waitFor();
 const dealt=page.waitForResponse(r=>r.url().endsWith('/deal')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Distribuisci',exact:true}).click();
 const state=await (await dealt).json();
 await page.getByLabel('Velocità distribuzione',{exact:true}).selectOption('250');
 assert.equal(await page.locator('.playing-card').nth(1).evaluate(element=>element.style.animationDelay),'250ms');
 await page.getByRole('button',{name:'Sistemi di conteggio',exact:true}).click();
 await page.locator('.counting-table tbody tr').first().waitFor();
 const rows=await page.locator('.counting-table tbody tr').count();
 assert.ok(rows>=7);
 const hilo=page.locator('.counting-table tr').filter({has:page.getByText('Hi-Lo',{exact:true})});
 assert.equal(await hilo.locator('td').nth(1).innerText(),'2.000');
 await page.getByRole('button',{name:'Valida e calcola',exact:true}).click();
 await page.locator('.custom-counter pre').waitFor();
 const counter=JSON.parse(await page.locator('.custom-counter pre').innerText());
 assert.equal(counter.counter.running_count,2);
 checks.push('All counting systems and validated custom tags use real exposed events');
 await page.screenshot({path:path.join(screenDir,'counting.png'),fullPage:true});
 await page.getByRole('button',{name:'Perception lab',exact:true}).click();
 await page.getByLabel('Design carte',{exact:true}).selectOption('minimal');
 const recognized=page.waitForResponse(r=>r.url().endsWith('/perception')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Analizza frame',exact:true}).click();
 const recognizedResult=await (await recognized).json();
 assert.ok(recognizedResult.detections.length>=3);
 assert.equal(recognizedResult.deck_estimation.mode,'KNOWN');
 assert.equal(recognizedResult.deck_estimation.decks,6);
 const observed=page.waitForResponse(r=>r.url().endsWith('/perception/analyze')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'EV dalla percezione',exact:true}).click();
 const analysis=await (await observed).json();
 assert.equal(analysis.status,'ok');
 assert.ok(analysis.result);
 checks.push('Observed-state EV endpoint uses reconstructed detections and reports precision');
 await page.getByRole('button',{name:'Apri strumenti',exact:true}).click();
 const image=await context.request.get(new URL('/api/sessions/'+state.session_id+'/frame',page.url()).href);
 const png=await image.body();
 await page.getByLabel('Immagine da calibrare').setInputFiles({name:'controlled-frame.png',mimeType:'image/png',buffer:png});
 const preview=page.locator('.calibration-preview');
 await preview.locator('img').waitFor();
 await page.waitForFunction(()=>{const image=document.querySelector('.calibration-preview img');return image&&image.complete&&image.naturalWidth>0});
 const bounds=await preview.boundingBox();
 for(const [x,y] of [[3,3],[bounds.width-3,3],[bounds.width-3,bounds.height-3],[3,bounds.height-3]])await preview.click({position:{x,y}});
 assert.equal(await preview.locator('span').count(),4);
 const imported=page.waitForResponse(r=>r.url().endsWith('/vision/upload')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Calibra e importa',exact:true}).click();
 const calibratedResponse=await imported;
 assert.equal(calibratedResponse.status(),200);
 const calibration=await calibratedResponse.json();
 assert.ok(calibration.detections.length>=3);
 assert.ok(calibration.calibration);
 assert.equal(calibration.deck_estimation.mode,'INFERRED');
 assert.equal(calibration.state.decks,null);
 await page.getByRole('region',{name:'Stima del numero di mazzi'}).getByText('Numero non determinato',{exact:true}).waitFor();
 assert.equal(await page.locator('.deck-posterior>div').count(),5);
 checks.push('Four clicked corners normalize pixels and preserve detections');
 await page.screenshot({path:path.join(screenDir,'calibration.png'),fullPage:true});
 if(videoFixture){
  await page.getByLabel('Un frame ogni',{exact:true}).fill('1');
  await page.getByLabel('Massimo frame',{exact:true}).fill('9');
  const videoResponse=page.waitForResponse(r=>r.url().includes('/vision/upload-video')&&r.request().method()==='POST');
  await page.locator('input[type=file][accept="video/*"]').setInputFiles(videoFixture);
  assert.equal((await videoResponse).status(),200);
  const viewer=page.getByRole('region',{name:'Replay dei frame video'});
  await viewer.waitFor();
  assert.equal(await page.locator('.observed-result').count(),0);
  await page.waitForFunction(()=>{const image=document.querySelector('.video-frame-wrap img');return image&&image.complete&&image.naturalWidth>0});
  assert.ok((await viewer.innerText()).includes('1 / 9'));
  const stateAtCursor=async()=>JSON.parse(await viewer.locator('details').first().locator('pre').innerText());
  assert.equal(Object.keys((await stateAtCursor()).cards).length,0);
  await page.getByRole('button',{name:'Frame successivo',exact:true}).click();
  assert.ok((await viewer.innerText()).includes('2 / 9'));
  await page.getByRole('button',{name:'Frame successivo',exact:true}).click();
  assert.ok(Object.keys((await stateAtCursor()).cards).length>=3);
  await page.getByRole('button',{name:'Frame precedente',exact:true}).click();
  await page.getByRole('button',{name:'Frame precedente',exact:true}).click();
  assert.ok((await viewer.innerText()).includes('1 / 9'));
  assert.equal(Object.keys((await stateAtCursor()).cards).length,0);
  await page.screenshot({path:path.join(screenDir,'video-replay.png'),fullPage:true});
  checks.push('Real JPEG video frames scrub backward without exposing later confirmed cards');
 }
 await page.getByRole('button',{name:'Esperimenti',exact:true}).click();
 await page.getByLabel('Round',{exact:true}).fill('100');
 await page.getByLabel('Seed',{exact:true}).fill('84');
 assert.ok((await page.locator('.top-status').innerText()).includes('Seed 42'));
 const experiment=page.waitForResponse(r=>r.url().endsWith('/api/experiments')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Esegui',exact:true}).click();
 const result=await (await experiment).json();
 assert.equal(result.completed_rounds,100);
 await page.locator('.policy-card').first().waitFor();
 assert.equal(await page.locator('.policy-card').count(),2);
 assert.ok(result.results.basic.ci95);
 checks.push('Executed policy experiment presents real means, paired uncertainty and raw samples');
 await page.screenshot({path:path.join(screenDir,'experiments.png'),fullPage:true});
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(root,'docs/BROWSER_ADVANCED_VERIFICATION.json'),JSON.stringify({passed:true,checks,errors,browser:'isolated Chrome headless'},null,2));
 console.log(JSON.stringify({passed:true,checks}));
}finally{await browser.close()}
