/** Hermetic application smoke test. Uses a fresh browser profile and only our local lab. */
import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const pw=require(process.argv[2]||process.env.BJLAB_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(import.meta.dirname,'../..');
console.log('Smoke: launch isolated Chrome');
const browser=await pw.chromium.launch({headless:true,channel:'chrome'});
console.log('Smoke: browser launched');
const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[];
const checks=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400&&r.url().includes('/api/'))errors.push(r.status()+' '+r.url())});
const screenDir=path.join(root,'docs/screenshots');fs.mkdirSync(screenDir,{recursive:true});
try{
 await page.goto(process.env.BJLAB_URL||'http://127.0.0.1:8765');
 console.log('Smoke: localhost loaded');
 await page.getByRole('button',{name:'Distribuisci',exact:true}).waitFor({state:'visible'});
 assert.equal(await page.locator('.playing-card').count(),0);
 checks.push('Initial native session, no fabricated cards');
 console.log('Smoke: native session ready');
 const analyzed=page.waitForResponse(r=>r.url().endsWith('/analyze')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Distribuisci',exact:true}).click();
 await page.getByRole('button',{name:'Raddoppia',exact:true}).waitFor({state:'visible'});
 await page.locator('.ev-row').first().waitFor({state:'visible',timeout:20000});
 assert.equal(await page.locator('.playing-card').count(),4);
 assert.equal(await page.getByLabel('Carta coperta').count(),1);
 const decision=await (await analyzed).json();
 assert.equal(decision.result.exact,true);
 assert.equal(decision.result.best_action,'double');
 assert.equal(decision.result.missing_actions?.length||0,0);
 checks.push('Seed42 live deal with hidden hole and mathematical EV results');
 console.log('Smoke: deal and EV verified');
 await page.screenshot({path:path.join(screenDir,'workbench.png'),fullPage:true});
 await page.getByRole('button',{name:'Perception lab',exact:true}).click();
 const responsePromise=page.waitForResponse(r=>r.url().endsWith('/perception')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Analizza frame',exact:true}).click();
 const perception=await (await responsePromise).json();
 assert.ok(perception.detections.length>=3);
 await page.locator('.detection-list').waitFor({state:'visible'});
 await page.getByRole('region',{name:'Metriche della percezione'}).waitFor({state:'visible'});
 assert.equal(await page.locator('.detection-overlay rect').count(),perception.detections.length);
 assert.ok(await page.locator('.vision-metrics').innerText().then(text=>text.includes('Non misurati')));
 assert.ok(await page.locator('.vision-metrics').innerText().then(text=>text.includes('1')));
 checks.push('Actual image rendering, pixel recognition and temporal reconstruction');
 await page.screenshot({path:path.join(screenDir,'perception.png'),fullPage:true});
 await page.getByRole('button',{name:'Replay & eventi',exact:true}).click();
 await page.locator('.event-list button').first().waitFor({state:'visible'});
 const replayPromise=page.waitForResponse(r=>r.url().endsWith('/api/replay')&&r.request().method()==='POST');
 await page.locator('.event-list button').nth(2).click();
 const replay=await (await replayPromise).json();
 assert.equal(replay.verified,true);
 assert.ok(replay.granularity.includes('exact event prefix'));
 checks.push('Event cursor reconstructs verified prefix without future exposure');
 await page.screenshot({path:path.join(screenDir,'replay.png'),fullPage:true});
 await page.getByRole('button',{name:'Tavolo & decisioni',exact:true}).click();
 await page.getByRole('button',{name:'Stai',exact:true}).click();
 await page.getByText('Mano conclusa',{exact:false}).first().waitFor({state:'visible'});
 assert.equal(await page.getByLabel('Carta coperta').count(),0);
 checks.push('Settlement reveals dealer and updates round result');
 await page.getByRole('button',{name:'Regolamento',exact:true}).click();
 await page.getByLabel('Mazzi',{exact:true}).selectOption('2');
 await page.getByRole('button',{name:'Applica e crea sessione',exact:true}).click();
 await page.getByRole('button',{name:'Tavolo & decisioni',exact:true}).click();
 await page.getByText('2 mazzi',{exact:false}).waitFor({state:'visible'});
 checks.push('Rules applied to new session, independent from prior hand');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(screenDir,'mobile.png'),fullPage:true});
 const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));
 assert.ok(dimensions.scroll<=dimensions.viewport+1,'Horizontal overflow: '+JSON.stringify(dimensions));
 checks.push('390px responsive layout without horizontal overflow');
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(root,'docs/BROWSER_VERIFICATION.json'),JSON.stringify({passed:true,checks,errors,screenshots:fs.readdirSync(screenDir),browser:'isolated Chrome headless',viewport:[1440,1050]},null,2));
 console.log(JSON.stringify({passed:true,checks}));
}finally{await browser.close()}
