import {localAddress,captureSelectedTab} from './capture.js';
const $=id=>document.getElementById(id);let image='';
const saved=await chrome.storage.local.get('address');if(saved.address)$('address').value=saved.address;
const status=text=>$('status').textContent=text;
async function request(path,body){const base=localAddress($('address').value);await chrome.storage.local.set({address:base});const response=await fetch(base+'/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok)throw new Error(result.detail||'Local analysis failed.');return result}
function show(report){$('result').hidden=false;$('action').textContent=report.advice?.best_action?.replaceAll('_',' ').toUpperCase()||'CONFIRM THE CARDS';const row=report.decision?.actions?.[report.advice?.best_action];$('details').textContent=report.advice?`${report.advice.hand.label} · ${report.advice.basis}${row?' · positive outcome '+(100*row.win).toFixed(1)+'%':''} · partial observed count`:report.gate?.reasons?.join(' ')||'Confirm the visible player cards and dealer upcard.';status('Local analysis complete. Earlier card history is unknown.')}
$('capture').onclick=async()=>{try{image=await captureSelectedTab(chrome.tabs);$('preview').src=image;$('preview').hidden=false;$('copy').disabled=false;$('analyze').disabled=false;$('result').hidden=true;status('Image captured. It stays local unless you analyze it against your local lab.')}catch(e){status(e.message)}};
$('copy').onclick=async()=>{try{const blob=await (await fetch(image)).blob();await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);status('Image copied. Paste it into the lab with Ctrl + V.')}catch(e){status(e.message)}};
$('analyze').onclick=async()=>{try{status('Reading image…');const rules=(await request('rules')).defaults;show(await request('advisor/image',{rules,image_base64:image.split(',')[1],player_turn:true}))}catch(e){status(e.message)}};
$('manual').onclick=async()=>{try{status('Analyzing confirmed cards…');const rules=(await request('rules')).defaults;show(await request('advisor/manual',{rules,player:$('player').value.trim().toUpperCase().split(/[\s,+]+/),dealer:$('dealer').value.trim().toUpperCase()}))}catch(e){status(e.message)}};
